In [2]:
from bs4 import BeautifulSoup
import requests
import random
from time import sleep
import pandas as pd
from pandas.io.json import json_normalize

In [105]:
from random import randint

In [166]:
pages_red = []
pages_white = []

In [168]:
#RED SPAIN
%%time

for i in range(1,100):

    response = requests.get(
    "https://www.vivino.com/api/explore/explore",
    params = {
        "country_codes[]":"es",
        "currency_code":"EUR",
        "page": i,
        "price_range_max":"1000",
        "price_range_min":"0",
        "wine_type_ids[]":"1"
    },
    headers= {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:66.0) Gecko/20100101 Firefox/66.0"
    }
)

    # store response into "pages" list
    pages_red.append(response)

    # respectful nap:
    wait_time = randint(1,4000)
    sleep(wait_time/1000)

CPU times: total: 1.91 s
Wall time: 5min 16s

In [172]:
%%time
# WHITE SPAIN

for i in range(1,100):

    response = requests.get(
    "https://www.vivino.com/api/explore/explore",
    params = {
        "country_codes[]":"es",
        "currency_code":"EUR",
        "page": i,
        "price_range_max":"1000",
        "price_range_min":"0",
        "wine_type_ids[]":"2"
    },
   headers = {"Accept-Language": "en-US"}
)

    # store response into "pages" list
    pages_white.append(response)

    # respectful nap:
    wait_time = randint(1,4000)
    sleep(wait_time/1000)

CPU times: total: 1.94 s
Wall time: 4min 27s

In [173]:
%%time
# RED PORTUGAL

for i in range(1,100):

    response = requests.get(
    "https://www.vivino.com/api/explore/explore",
    params = {
        "country_codes[]":"pt",
        "currency_code":"EUR",
        "page": i,
        "price_range_max":"1000",
        "price_range_min":"0",
        "wine_type_ids[]":"1"
    },
    headers= {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:66.0) Gecko/20100101 Firefox/66.0"
    }
)

    # store response into "pages" list
    pages_red.append(response)

    # respectful nap:
    wait_time = randint(1,4000)
    sleep(wait_time/1000)

CPU times: total: 1.86 s
Wall time: 4min 49s

In [174]:
%%time
# WHITE PORTUGAL

for i in range(1,100):

    response = requests.get(
    "https://www.vivino.com/api/explore/explore",
    params = {
        "country_codes[]":"pt",
        "currency_code":"EUR",
        "page": i,
        "price_range_max":"1000",
        "price_range_min":"0",
        "wine_type_ids[]":"2"
    },
    headers= {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:66.0) Gecko/20100101 Firefox/66.0"
    }
)

    # store response into "pages" list
    pages_white.append(response)

    # respectful nap:
    wait_time = randint(1,4000)
    sleep(wait_time/1000)

CPU times: total: 1.67 s
Wall time: 4min 18s

In [175]:
%%time
# RED ITALY

for i in range(1,100):

    response = requests.get(
    "https://www.vivino.com/api/explore/explore",
    params = {
        "country_codes[]":"it",
        "currency_code":"EUR",
        "page": i,
        "price_range_max":"1000",
        "price_range_min":"0",
        "wine_type_ids[]":"1"
    },
    headers= {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:66.0) Gecko/20100101 Firefox/66.0"
    }
)

    # store response into "pages" list
    pages_red.append(response)

    # respectful nap:
    wait_time = randint(1,4000)
    sleep(wait_time/1000)

CPU times: total: 1.8 s
Wall time: 4min 59s

In [176]:
%%time
# WHITE ITALY

for i in range(1,100):

    response = requests.get(
    "https://www.vivino.com/api/explore/explore",
    params = {
        "country_codes[]":"it",
        "currency_code":"EUR",
        "page": i,
        "price_range_max":"1000",
        "price_range_min":"0",
        "wine_type_ids[]":"2"
    },
    headers= {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:66.0) Gecko/20100101 Firefox/66.0"
    }
)

    # store response into "pages" list
    pages_white.append(response)

    # respectful nap:
    wait_time = randint(1,4000)
    sleep(wait_time/1000)

CPU times: total: 1.84 s
Wall time: 4min 51s

In [177]:
%%time
# RED BELGIUM

for i in range(1,100):

    response = requests.get(
    "https://www.vivino.com/api/explore/explore",
    params = {
        "country_codes[]":"be",
        "currency_code":"EUR",
        "page": i,
        "price_range_max":"1000",
        "price_range_min":"0",
        "wine_type_ids[]":"1"
    },
    headers= {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:66.0) Gecko/20100101 Firefox/66.0"
    }
)

    # store response into "pages" list
    pages_red.append(response)

    # respectful nap:
    wait_time = randint(1,4000)
    sleep(wait_time/1000)

CPU times: total: 1.8 s
Wall time: 3min 50s

In [178]:
%%time
# WHITE BELGIUM

for i in range(1,100):

    response = requests.get(
    "https://www.vivino.com/api/explore/explore",
    params = {
        "country_codes[]":"be",
        "currency_code":"EUR",
        "page": i,
        "price_range_max":"1000",
        "price_range_min":"0",
        "wine_type_ids[]":"2"
    },
    headers= {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:66.0) Gecko/20100101 Firefox/66.0"
    }
)

    # store response into "pages" list
    pages_white.append(response)

    # respectful nap:
    wait_time = randint(1,4000)
    sleep(wait_time/1000)

CPU times: total: 1.94 s
Wall time: 3min 58s

In [179]:
%%time
# RED FRANCE


for i in range(1,100):

    response = requests.get(
    "https://www.vivino.com/api/explore/explore",
    params = {
        "country_codes[]":"fr",
        "currency_code":"EUR",
        "page": i,
        "price_range_max":"1000",
        "price_range_min":"0",
        "wine_type_ids[]":"1"
    },
    headers= {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:66.0) Gecko/20100101 Firefox/66.0"
    }
)

    # store response into "pages" list
    pages_red.append(response)

    # respectful nap:
    wait_time = randint(1,4000)
    sleep(wait_time/1000)

CPU times: total: 1.8 s
Wall time: 4min 59s

In [180]:
%%time
# WHITE FRANCE


for i in range(1,100):

    response = requests.get(
    "https://www.vivino.com/api/explore/explore",
    params = {
        "country_codes[]":"fr",
        "currency_code":"EUR",
        "page": i,
        "price_range_max":"1000",
        "price_range_min":"0",
        "wine_type_ids[]":"2"
    },
    headers= {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:66.0) Gecko/20100101 Firefox/66.0"
    }
)

    # store response into "pages" list
    pages_white.append(response)

    # respectful nap:
    wait_time = randint(1,4000)
    sleep(wait_time/1000)

CPU times: total: 1.66 s
Wall time: 4min 56s

In [181]:
%%time
# RED US


for i in range(1,100):

    response = requests.get(
    "https://www.vivino.com/api/explore/explore",
    params = {
        "country_codes[]":"us",
        "currency_code":"EUR",
        "page": i,
        "price_range_max":"1000",
        "price_range_min":"0",
        "wine_type_ids[]":"1"
    },
    headers= {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:66.0) Gecko/20100101 Firefox/66.0"
    }
)

    # store response into "pages" list
    pages_red.append(response)

    # respectful nap:
    wait_time = randint(1,4000)
    sleep(wait_time/1000)

CPU times: total: 1.41 s
Wall time: 4min 6s

In [182]:
%%time
# WHITE US


for i in range(1,100):

    response = requests.get(
    "https://www.vivino.com/api/explore/explore",
    params = {
        "country_codes[]":"us",
        "currency_code":"EUR",
        "page": i,
        "price_range_max":"1000",
        "price_range_min":"0",
        "wine_type_ids[]":"2"
    },
    headers= {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:66.0) Gecko/20100101 Firefox/66.0"
    }
)

    # store response into "pages" list
    pages_white.append(response)

    # respectful nap:
    wait_time = randint(1,4000)
    sleep(wait_time/1000)

CPU times: total: 1.36 s
Wall time: 3min 51s

In [183]:
%%time
# RED ARGENTINA


for i in range(1,100):

    response = requests.get(
    "https://www.vivino.com/api/explore/explore",
    params = {
        "country_codes[]":"ar",
        "currency_code":"EUR",
        "page": i,
        "price_range_max":"1000",
        "price_range_min":"0",
        "wine_type_ids[]":"1"
    },
    headers= {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:66.0) Gecko/20100101 Firefox/66.0"
    }
)

    # store response into "pages" list
    pages_red.append(response)

    # respectful nap:
    wait_time = randint(1,4000)
    sleep(wait_time/1000)

CPU times: total: 1.7 s
Wall time: 4min 6s

In [184]:
%%time
# WHITE ARGENTINA


for i in range(1,100):

    response = requests.get(
    "https://www.vivino.com/api/explore/explore",
    params = {
        "country_codes[]":"ar",
        "currency_code":"EUR",
        "page": i,
        "price_range_max":"1000",
        "price_range_min":"0",
        "wine_type_ids[]":"2"
    },
    headers= {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:66.0) Gecko/20100101 Firefox/66.0"
    }
)

    # store response into "pages" list
    pages_white.append(response)

    # respectful nap:
    wait_time = randint(1,4000)
    sleep(wait_time/1000)

CPU times: total: 1.47 s
Wall time: 4min 9s

In [185]:
%%time
# RED switzerland


for i in range(1,100):

    response = requests.get(
    "https://www.vivino.com/api/explore/explore",
    params = {
        "country_codes[]":"ch",
        "currency_code":"EUR",
        "page": i,
        "price_range_max":"1000",
        "price_range_min":"0",
        "wine_type_ids[]":"1"
    },
    headers= {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:66.0) Gecko/20100101 Firefox/66.0"
    }
)

    # store response into "pages" list
    pages_red.append(response)

    # respectful nap:
    wait_time = randint(1,4000)
    sleep(wait_time/1000)

CPU times: total: 1.41 s
Wall time: 3min 42s

In [186]:
%%time
# WHITE switzerland


for i in range(1,100):

    response = requests.get(
    "https://www.vivino.com/api/explore/explore",
    params = {
        "country_codes[]":"ch",
        "currency_code":"EUR",
        "page": i,
        "price_range_max":"1000",
        "price_range_min":"0",
        "wine_type_ids[]":"2"
    },
    headers= {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:66.0) Gecko/20100101 Firefox/66.0"
    }
)

    # store response into "pages" list
    pages_white.append(response)

    # respectful nap:
    wait_time = randint(1,4000)
    sleep(wait_time/1000)

CPU times: total: 1.25 s
Wall time: 3min 40s

In [187]:
%%time
# RED NEW ZELAND


for i in range(1,100):

    response = requests.get(
    "https://www.vivino.com/api/explore/explore",
    params = {
        "country_codes[]":"nz",
        "currency_code":"EUR",
        "page": i,
        "price_range_max":"1000",
        "price_range_min":"0",
        "wine_type_ids[]":"1"
    },
    headers= {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:66.0) Gecko/20100101 Firefox/66.0"
    }
)

    # store response into "pages" list
    pages_red.append(response)

    # respectful nap:
    wait_time = randint(1,4000)
    sleep(wait_time/1000)

CPU times: total: 1.41 s
Wall time: 3min 53s

In [188]:
%%time
# WHITE NEW ZELAND


for i in range(1,100):

    response = requests.get(
    "https://www.vivino.com/api/explore/explore",
    params = {
        "country_codes[]":"nz",
        "currency_code":"EUR",
        "page": i,
        "price_range_max":"1000",
        "price_range_min":"0",
        "wine_type_ids[]":"2"
    },
    headers= {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:66.0) Gecko/20100101 Firefox/66.0"
    }
)

    # store response into "pages" list
    pages_white.append(response)

    # respectful nap:
    wait_time = randint(1,4000)
    sleep(wait_time/1000)

CPU times: total: 1.52 s
Wall time: 4min 13s

In [187]:
%%time
# RED CHILE


for i in range(1,100):

    response = requests.get(
    "https://www.vivino.com/api/explore/explore",
    params = {
        "country_codes[]":"cl",
        "currency_code":"EUR",
        "page": i,
        "price_range_max":"1000",
        "price_range_min":"0",
        "wine_type_ids[]":"1"
    },
    headers= {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:66.0) Gecko/20100101 Firefox/66.0"
    }
)

    # store response into "pages" list
    pages_red.append(response)

    # respectful nap:
    wait_time = randint(1,4000)
    sleep(wait_time/1000)

CPU times: total: 1.41 s
Wall time: 3min 53s

In [188]:
%%time
# WHITE CHILE


for i in range(1,100):

    response = requests.get(
    "https://www.vivino.com/api/explore/explore",
    params = {
        "country_codes[]":"cl",
        "currency_code":"EUR",
        "page": i,
        "price_range_max":"1000",
        "price_range_min":"0",
        "wine_type_ids[]":"2"
    },
    headers= {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:66.0) Gecko/20100101 Firefox/66.0"
    }
)

    # store response into "pages" list
    pages_white.append(response)

    # respectful nap:
    wait_time = randint(1,4000)
    sleep(wait_time/1000)

CPU times: total: 1.52 s
Wall time: 4min 13s

In [187]:
%%time
# RED AUSTRALIA


for i in range(1,100):

    response = requests.get(
    "https://www.vivino.com/api/explore/explore",
    params = {
        "country_codes[]":"au",
        "currency_code":"EUR",
        "page": i,
        "price_range_max":"1000",
        "price_range_min":"0",
        "wine_type_ids[]":"1"
    },
    headers= {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:66.0) Gecko/20100101 Firefox/66.0"
    }
)

    # store response into "pages" list
    pages_red.append(response)

    # respectful nap:
    wait_time = randint(1,4000)
    sleep(wait_time/1000)

CPU times: total: 1.41 s
Wall time: 3min 53s

In [188]:
%%time
# WHITE AUSTRALIA


for i in range(1,100):

    response = requests.get(
    "https://www.vivino.com/api/explore/explore",
    params = {
        "country_codes[]":"au",
        "currency_code":"EUR",
        "page": i,
        "price_range_max":"1000",
        "price_range_min":"0",
        "wine_type_ids[]":"2"
    },
    headers= {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:66.0) Gecko/20100101 Firefox/66.0"
    }
)

    # store response into "pages" list
    pages_white.append(response)

    # respectful nap:
    wait_time = randint(1,4000)
    sleep(wait_time/1000)

CPU times: total: 1.52 s
Wall time: 4min 13s

In [187]:
%%time
# RED CHINA


for i in range(1,100):

    response = requests.get(
    "https://www.vivino.com/api/explore/explore",
    params = {
        "country_codes[]":"cn",
        "currency_code":"EUR",
        "page": i,
        "price_range_max":"1000",
        "price_range_min":"0",
        "wine_type_ids[]":"1"
    },
    headers= {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:66.0) Gecko/20100101 Firefox/66.0"
    }
)

    # store response into "pages" list
    pages_red.append(response)

    # respectful nap:
    wait_time = randint(1,4000)
    sleep(wait_time/1000)

CPU times: total: 1.41 s
Wall time: 3min 53s

In [188]:
%%time
# WHITE CHINA


for i in range(1,100):

    response = requests.get(
    "https://www.vivino.com/api/explore/explore",
    params = {
        "country_codes[]":"cn",
        "currency_code":"EUR",
        "page": i,
        "price_range_max":"1000",
        "price_range_min":"0",
        "wine_type_ids[]":"2"
    },
    headers= {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:66.0) Gecko/20100101 Firefox/66.0"
    }
)

    # store response into "pages" list
    pages_white.append(response)

    # respectful nap:
    wait_time = randint(1,4000)
    sleep(wait_time/1000)

CPU times: total: 1.52 s
Wall time: 4min 13s

In [187]:
%%time
# RED SOUTH AFRICA


for i in range(1,100):

    response = requests.get(
    "https://www.vivino.com/api/explore/explore",
    params = {
        "country_codes[]":"za",
        "currency_code":"EUR",
        "page": i,
        "price_range_max":"1000",
        "price_range_min":"0",
        "wine_type_ids[]":"1"
    },
    headers= {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:66.0) Gecko/20100101 Firefox/66.0"
    }
)

    # store response into "pages" list
    pages_red.append(response)

    # respectful nap:
    wait_time = randint(1,4000)
    sleep(wait_time/1000)

CPU times: total: 1.41 s
Wall time: 3min 53s

In [188]:
%%time
# WHITE SOUTH AFRICA


for i in range(1,100):

    response = requests.get(
    "https://www.vivino.com/api/explore/explore",
    params = {
        "country_codes[]":"za",
        "currency_code":"EUR",
        "page": i,
        "price_range_max":"1000",
        "price_range_min":"0",
        "wine_type_ids[]":"2"
    },
    headers= {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:66.0) Gecko/20100101 Firefox/66.0"
    }
)

    # store response into "pages" list
    pages_white.append(response)

    # respectful nap:
    wait_time = randint(1,4000)
    sleep(wait_time/1000)

CPU times: total: 1.52 s
Wall time: 4min 13s

In [187]:
%%time
# RED GEORGIA


for i in range(1,100):

    response = requests.get(
    "https://www.vivino.com/api/explore/explore",
    params = {
        "country_codes[]":"ge",
        "currency_code":"EUR",
        "page": i,
        "price_range_max":"1000",
        "price_range_min":"0",
        "wine_type_ids[]":"1"
    },
    headers= {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:66.0) Gecko/20100101 Firefox/66.0"
    }
)

    # store response into "pages" list
    pages_red.append(response)

    # respectful nap:
    wait_time = randint(1,4000)
    sleep(wait_time/1000)

CPU times: total: 1.41 s
Wall time: 3min 53s

In [188]:
%%time
# WHITE GEORGIA


for i in range(1,100):

    response = requests.get(
    "https://www.vivino.com/api/explore/explore",
    params = {
        "country_codes[]":"ge",
        "currency_code":"EUR",
        "page": i,
        "price_range_max":"1000",
        "price_range_min":"0",
        "wine_type_ids[]":"2"
    },
    headers= {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:66.0) Gecko/20100101 Firefox/66.0"
    }
)

    # store response into "pages" list
    pages_white.append(response)

    # respectful nap:
    wait_time = randint(1,4000)
    sleep(wait_time/1000)

CPU times: total: 1.52 s
Wall time: 4min 13s

In [187]:
%%time
# RED GERMANY


for i in range(1,100):

    response = requests.get(
    "https://www.vivino.com/api/explore/explore",
    params = {
        "country_codes[]":"de",
        "currency_code":"EUR",
        "page": i,
        "price_range_max":"1000",
        "price_range_min":"0",
        "wine_type_ids[]":"1"
    },
    headers= {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:66.0) Gecko/20100101 Firefox/66.0"
    }
)

    # store response into "pages" list
    pages_red.append(response)

    # respectful nap:
    wait_time = randint(1,4000)
    sleep(wait_time/1000)

CPU times: total: 1.41 s
Wall time: 3min 53s

In [188]:
%%time
# WHITE GERMANY


for i in range(1,100):

    response = requests.get(
    "https://www.vivino.com/api/explore/explore",
    params = {
        "country_codes[]":"de",
        "currency_code":"EUR",
        "page": i,
        "price_range_max":"1000",
        "price_range_min":"0",
        "wine_type_ids[]":"2"
    },
    headers= {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:66.0) Gecko/20100101 Firefox/66.0"
    }
)

    # store response into "pages" list
    pages_white.append(response)

    # respectful nap:
    wait_time = randint(1,4000)
    sleep(wait_time/1000)

CPU times: total: 1.52 s
Wall time: 4min 13s

In [187]:
%%time
# RED ROMANIA

for i in range(1,100):

    response = requests.get(
    "https://www.vivino.com/api/explore/explore",
    params = {
        "country_codes[]":"ro",
        "currency_code":"EUR",
        "page": i,
        "price_range_max":"1000",
        "price_range_min":"0",
        "wine_type_ids[]":"1"
    },
    headers= {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:66.0) Gecko/20100101 Firefox/66.0"
    }
)

    # store response into "pages" list
    pages_red.append(response)

    # respectful nap:
    wait_time = randint(1,4000)
    sleep(wait_time/1000)

CPU times: total: 1.41 s
Wall time: 3min 53s

In [188]:
%%time
# WHITE ROMANIA


for i in range(1,100):

    response = requests.get(
    "https://www.vivino.com/api/explore/explore",
    params = {
        "country_codes[]":"ro",
        "currency_code":"EUR",
        "page": i,
        "price_range_max":"1000",
        "price_range_min":"0",
        "wine_type_ids[]":"2"
    },
    headers= {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:66.0) Gecko/20100101 Firefox/66.0"
    }
)

    # store response into "pages" list
    pages_white.append(response)

    # respectful nap:
    wait_time = randint(1,4000)
    sleep(wait_time/1000)

CPU times: total: 1.52 s
Wall time: 4min 13s

In [187]:
%%time
# RED RUSSIA


for i in range(1,100):

    response = requests.get(
    "https://www.vivino.com/api/explore/explore",
    params = {
        "country_codes[]":"ru",
        "currency_code":"EUR",
        "page": i,
        "price_range_max":"1000",
        "price_range_min":"0",
        "wine_type_ids[]":"1"
    },
    headers= {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:66.0) Gecko/20100101 Firefox/66.0"
    }
)

    # store response into "pages" list
    pages_red.append(response)

    # respectful nap:
    wait_time = randint(1,4000)
    sleep(wait_time/1000)

CPU times: total: 1.41 s
Wall time: 3min 53s

In [188]:
%%time
# WHITE RUSSIA


for i in range(1,100):

    response = requests.get(
    "https://www.vivino.com/api/explore/explore",
    params = {
        "country_codes[]":"ru",
        "currency_code":"EUR",
        "page": i,
        "price_range_max":"1000",
        "price_range_min":"0",
        "wine_type_ids[]":"2"
    },
    headers= {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:66.0) Gecko/20100101 Firefox/66.0"
    }
)

    # store response into "pages" list
    pages_white.append(response)

    # respectful nap:
    wait_time = randint(1,4000)
    sleep(wait_time/1000)

CPU times: total: 1.52 s
Wall time: 4min 13s

In [187]:
%%time
# RED ISRAEL


for i in range(1,100):

    response = requests.get(
    "https://www.vivino.com/api/explore/explore",
    params = {
        "country_codes[]":"il",
        "currency_code":"EUR",
        "page": i,
        "price_range_max":"1000",
        "price_range_min":"0",
        "wine_type_ids[]":"1"
    },
    headers= {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:66.0) Gecko/20100101 Firefox/66.0"
    }
)

    # store response into "pages" list
    pages_red.append(response)

    # respectful nap:
    wait_time = randint(1,4000)
    sleep(wait_time/1000)

CPU times: total: 1.41 s
Wall time: 3min 53s

In [188]:
%%time
# WHITE ISRAEL


for i in range(1,100):

    response = requests.get(
    "https://www.vivino.com/api/explore/explore",
    params = {
        "country_codes[]":"il",
        "currency_code":"EUR",
        "page": i,
        "price_range_max":"1000",
        "price_range_min":"0",
        "wine_type_ids[]":"2"
    },
    headers= {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:66.0) Gecko/20100101 Firefox/66.0"
    }
)

    # store response into "pages" list
    pages_white.append(response)

    # respectful nap:
    wait_time = randint(1,4000)
    sleep(wait_time/1000)

CPU times: total: 1.52 s
Wall time: 4min 13s

In [187]:
%%time
# RED BRASIL


for i in range(1,100):

    response = requests.get(
    "https://www.vivino.com/api/explore/explore",
    params = {
        "country_codes[]":"br",
        "currency_code":"EUR",
        "page": i,
        "price_range_max":"1000",
        "price_range_min":"0",
        "wine_type_ids[]":"1"
    },
    headers= {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:66.0) Gecko/20100101 Firefox/66.0"
    }
)

    # store response into "pages" list
    pages_red.append(response)

    # respectful nap:
    wait_time = randint(1,4000)
    sleep(wait_time/1000)

CPU times: total: 1.41 s
Wall time: 3min 53s

In [188]:
%%time
# WHITE BRASIL


for i in range(1,100):

    response = requests.get(
    "https://www.vivino.com/api/explore/explore",
    params = {
        "country_codes[]":"br",
        "currency_code":"EUR",
        "page": i,
        "price_range_max":"1000",
        "price_range_min":"0",
        "wine_type_ids[]":"2"
    },
    headers= {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:66.0) Gecko/20100101 Firefox/66.0"
    }
)

    # store response into "pages" list
    pages_white.append(response)

    # respectful nap:
    wait_time = randint(1,4000)
    sleep(wait_time/1000)

CPU times: total: 1.52 s
Wall time: 4min 13s

In [189]:
len(pages_red)

927

In [197]:
len(pages_red[0].json()['explore_vintage']['matches'])

25

In [190]:
len(pages_white)

891

In [221]:
len(results_red_total)

2

## GETTING DATAFRAMES

### Wine

In [473]:
def getting_df(pages, cols_names):
    
    results_total = []
    
    for j in range(len(pages)):
        results = [(
            t["vintage"]["id"],
            t["vintage"]["name"],
            t['vintage']['wine']['winery']['name'],
            t['vintage']['wine']['type_id'],
            t['vintage']['wine']['region']['name'],
            t['vintage']['wine']['region']['country']['seo_name'],
            t['vintage']['year'],
            t['vintage']['statistics']['wine_ratings_count'],
            t['vintage']['statistics']['wine_ratings_average']
        )
    for t in pages[j].json()['explore_vintage']['matches']
    ]
        results_total.append(results)
    
    
    df1 = pd.DataFrame(results_total[0],columns=cols_names)
    
    
    for i in range(1,len(results_total)):
        df = pd.DataFrame(results_total[i],columns=cols_names)
        df1 = pd.concat([df1,df],axis=0)
    
    return df1

In [474]:
cols_wine = ['wine_id','wine_name','winery','type','region','country','year','num_ratings','rate']

#### RED WINES

In [475]:
df_red = getting_df(pages_red, cols_wine)
df_red

,wine_id,wine_name,winery,type,region,country,year,num_ratings,rate
0,1420799,Vega Sicilia Unico 2009,Vega Sicilia,1,Ribera del Duero,spain,2009,43244,4.7
1,1199830,Vega Sicilia Unico 1999,Vega Sicilia,1,Ribera del Duero,spain,1999,43244,4.7
2,1494622,Vega Sicilia Unico 2010,Vega Sicilia,1,Ribera del Duero,spain,2010,43244,4.7
3,1229417,Vega Sicilia Unico 1996,Vega Sicilia,1,Ribera del Duero,spain,1996,43244,4.7
4,87412043,Vega Sicilia Unico Reserva Especial Edición 2016,Vega Sicilia,1,Ribera del Duero,spain,2016,12808,4.7
...,...,...,...,...,...,...,...,...,...
19,165841668,Black Cottage Pinot Noir 2020,Black Cottage,1,Marlborough,new-zealand,2020,997,3.6
20,146488410,Terroirs Pinot Noir 2016,Terroirs,1,Marlborough,new-zealand,2016,64,3.1
21,162784956,Trinity Hill L'Eritage Syrah 2018,Trinity Hill,1,Gimblett Gravels,new-zealand,2018,0,0.0
22,161457754,De la Terre Grand Reserve Tannat 2016,De la Terre,1,"Hawke""s Bay",new-zealand,2016,0,0.0
23,165159053,Pisa Range Estate Soli Vero Pinot Noir 2018,Pisa Range Estate,1,Central Otago,new-zealand,2018,0,0.0

#### WHITE WINES

In [289]:
df_white = getting_df(pages_white, cols_wine)
df_white

,wine_id,wine_name,winery,type,region,country,year,num_ratings,rate
0,150105832,Marqués de Murrieta Castillo Ygay Gran Reserva...,Marqués de Murrieta,2,Rioja,spain,1986,2463,4.6
1,157149853,Allende Martires Rioja 2018,Allende,2,Rioja,spain,2018,440,4.4
2,168045671,Olivier Rivière Mirando al Sur 2018,Olivier Rivière,2,Rioja,spain,2018,374,4.4
3,160958478,Bodegas Frontonio El Jardín de las Iguales Viñ...,Bodegas Frontonio,2,Valdejalón,spain,2016,43,4.6
4,169589078,Pazo Barrantes Gran Vino Albariño 2019,Pazo Barrantes,2,Rías Baixas,spain,2019,716,4.5
...,...,...,...,...,...,...,...,...,...
22,161079706,Carrick Bannockburn Pinot Gris 2018,Carrick,2,Bannockburn,new-zealand,2018,131,3.6
23,166755107,Pegasus Bay Gewürztraminer 2019,Pegasus Bay,2,Waipara,new-zealand,2019,128,3.6
24,152800051,Vidal Chardonnay 2016,Vidal,2,"Hawke""s Bay",new-zealand,2016,150,3.6
0,159078719,Longridge Chardonnay 2018,Longridge,2,"Hawke""s Bay",new-zealand,2018,51,3.5
1,162602887,Eaton Thistle Hill Sauvignon Blanc 2018,Eaton,2,Marlborough,new-zealand,2018,0,0.0

#### Concat and Save dataframe

In [290]:
df_wines = pd.concat([df_red,df_white],axis=0)

In [291]:
df_wines.to_csv('scraping_wines.csv')

### Purchase

In [294]:
def getting_purchase(pages, cols_names):
    
    results_total = []
    
    for j in range(len(pages)):
        results = [(
        t["vintage"]["id"],
        t['price']['amount'],
        t['price']['currency']['code'],
        t['price']['bottle_type']['id'],
        t['price']['bottle_type']['short_name'],
        t['price']['bottle_type']['volume_ml']
        )
    for t in pages[j].json()['explore_vintage']['matches']
    ]
       
        results_total.append(results)
    
    
    df1 = pd.DataFrame(results_total[0],columns=cols_names)
    
    
    for i in range(1,len(results_total)):
        df = pd.DataFrame(results_total[i],columns=cols_names)
        df1 = pd.concat([df1,df],axis=0)
    
    return df1

In [292]:
cols_purchase = ['wine_id','price','currency','bottle_type_id','bottle_type','vol_ml']

#### RED WINES

In [295]:
purchase_red = getting_purchase(pages_red, cols_purchase)
purchase_red

      wine_id price_euros bottle_type_id bottle_type vol_ml
0     1420799       487.0              1     botella    750
1     1199830      692.96              1     botella    750
2     1494622      380.55              1     botella    750
3     1229417      778.06              1     botella    750
4    87412043      514.85              1     botella    750
..        ...         ...            ...         ...    ...
19  165841668       17.45              1     botella    750
20  146488410        29.6              1     botella    750
21  162784956    77.66494              1     botella    750
22  161457754   37.116291              1     botella    750
23  165159053   31.976322              1     botella    750

[11878 rows x 5 columns]

#### WHITE WINES

In [296]:
purchase_white = getting_purchase(pages_white, cols_purchase)
purchase_white

      wine_id price_euros bottle_type_id bottle_type vol_ml
0   150105832       795.0              1     botella    750
1   157149853      108.63              1     botella    750
2   168045671        74.0              1     botella    750
3   160958478       174.9              1     botella    750
4   169589078        34.9              1     botella    750
..        ...         ...            ...         ...    ...
22  161079706   15.699751              1     botella    750
23  166755107   18.441068              1     botella    750
24  152800051   74.238293              1     botella    750
0   159078719       18.95              1     botella    750
1   162602887    27.40746              1     botella    750

[7810 rows x 5 columns]

#### Concat and Save dataframe

In [297]:
df_purchase = pd.concat([purchase_red,purchase_white],axis=0)

In [298]:
df_purchase.to_csv('scraping_purchase.csv')

### Style & Taste

In [529]:
cols_style = ['wine_id','varietal_name','body','acidity_1','acidity_description','acidity_2','fizziness','intensity','sweetness','tannin']

In [612]:
# def getting_style(pages, cols_names):
#     results_total = []
    
#     for j in range(len(pages)):
#         print(j)
#         for i in range(len(pages[j].json()['explore_vintage']['matches'])):
#             if len(pages[j].json()['explore_vintage']['matches'][i]['vintage']['wine']['style'].keys())>7:
#                 try:
#                     results = [(t["vintage"]["id"],t['vintage']['wine']['style']['varietal_name'],t['vintage']['wine']['style']['body'],t['vintage']['wine']['style']['acidity'],t['vintage']['wine']['style']['acidity_description'],t['vintage']['wine']['taste']['structure']['acidity'],t['vintage']['wine']['taste']['structure']['fizziness'],t['vintage']['wine']['taste']['structure']['intensity'],t['vintage']['wine']['taste']['structure']['sweetness'],t['vintage']['wine']['taste']['structure']['tannin'])for t in pages[j].json()['explore_vintage']['matches'] ]
#                     results_total.append(results)
#                 except:
#                     results = [(t["vintage"]["id"],t['vintage']['wine']['style']['id'],t['vintage']['wine']['style']['id'],t['vintage']['wine']['style']['id'],t['vintage']['wine']['style']['id'],t['vintage']['wine']['style']['id'],t['vintage']['wine']['style']['id'],t['vintage']['wine']['style']['id'],t['vintage']['wine']['style']['id'],t['vintage']['wine']['style']['id'])for t in pages[j].json()['explore_vintage']['matches']]
#                     results_total.append(results)
#             else:
#                 try:
#                     results = [(t["vintage"]["id"],t['vintage']['wine']['style']['varietal_name'],t['vintage']['wine']['style']['id'],t['vintage']['wine']['style']['id'],t['vintage']['wine']['style']['id'],t['vintage']['wine']['style']['id'],t['vintage']['wine']['style']['id'],t['vintage']['wine']['style']['id'], t['vintage']['wine']['style']['id'],t['vintage']['wine']['style']['id'])for t in pages[j].json()['explore_vintage']['matches']]
#                     results_total.append(results)
#                 except:
#                     results = [(t["vintage"]["id"],t['vintage']['id'],t['vintage']['id'],t['vintage']['id'],t['vintage']['id'],t['vintage']['id'],t['vintage']['id'],t['vintage']['id'],t['vintage']['id'],t['vintage']['id'])for t in pages[j].json()['explore_vintage']['matches']]
#                     results_total.append(results)
    
    
#     df1 = pd.DataFrame(results_total[0],columns=cols_names)
    
    
#     for k in range(1,len(results_total)):
#         df = pd.DataFrame(results_total[k],columns=cols_names)
#         df1 = pd.concat([df1,df],axis=0)
    
#     return df1

In [624]:
# def getting_style(pages, cols_names):
#     results_total = []
    
#     for j in range(len(pages)):
#         print(j)
#         for i in range(len(pages[j].json()['explore_vintage']['matches'])):
#             if pages[j].json()['explore_vintage']['matches'][i]['vintage']['wine']['style']!=None:
#                 if len(pages[j].json()['explore_vintage']['matches'][i]['vintage']['wine']['style'])>7:
#                     results = [(
#                         pages[j].json()['explore_vintage']['matches'][i]["vintage"]["id"],
#                         pages[j].json()['explore_vintage']['matches'][i]['vintage']['wine']['style']['varietal_name'],
#                         pages[j].json()['explore_vintage']['matches'][i]['vintage']['wine']['style']['body'],
#                         pages[j].json()['explore_vintage']['matches'][i]['vintage']['wine']['style']['acidity'],
#                         pages[j].json()['explore_vintage']['matches'][i]['vintage']['wine']['style']['acidity_description'],
#                         pages[j].json()['explore_vintage']['matches'][i]['vintage']['wine']['taste']['structure']['acidity'],
#                         pages[j].json()['explore_vintage']['matches'][i]['vintage']['wine']['taste']['structure']['fizziness'],
#                         pages[j].json()['explore_vintage']['matches'][i]['vintage']['wine']['taste']['structure']['intensity'],
#                         pages[j].json()['explore_vintage']['matches'][i]['vintage']['wine']['taste']['structure']['sweetness'],
#                         pages[j].json()['explore_vintage']['matches'][i]['vintage']['wine']['taste']['structure']['tannin']
#                     )]
#                     results_total.append(results)
#                 else:
#                     results = [(
#                         pages[j].json()['explore_vintage']['matches'][i]["vintage"]["id"],
#                         pages[j].json()['explore_vintage']['matches'][i]['vintage']['wine']['style']['varietal_name'],
#                         pages[j].json()['explore_vintage']['matches'][i]['vintage']['wine']['style']['id'],
#                         pages[j].json()['explore_vintage']['matches'][i]['vintage']['wine']['style']['id'],
#                         pages[j].json()['explore_vintage']['matches'][i]['vintage']['wine']['style']['id'],
#                         pages[j].json()['explore_vintage']['matches'][i]['vintage']['wine']['style']['id'],
#                         pages[j].json()['explore_vintage']['matches'][i]['vintage']['wine']['style']['id'],
#                         pages[j].json()['explore_vintage']['matches'][i]['vintage']['wine']['style']['id'],
#                         pages[j].json()['explore_vintage']['matches'][i]['vintage']['wine']['style']['id'],
#                         pages[j].json()['explore_vintage']['matches'][i]['vintage']['wine']['style']['id']
#                     )]
#                     results_total.append(results)
#             else:
#                 results = [(
#                     pages[j].json()['explore_vintage']['matches'][i]["vintage"]["id"],
#                     pages[j].json()['explore_vintage']['matches'][i]['vintage']["id"],
#                     pages[j].json()['explore_vintage']['matches'][i]['vintage']["id"],
#                     pages[j].json()['explore_vintage']['matches'][i]['vintage']["id"],
#                     pages[j].json()['explore_vintage']['matches'][i]['vintage']["id"],
#                     pages[j].json()['explore_vintage']['matches'][i]['vintage']["id"],
#                     pages[j].json()['explore_vintage']['matches'][i]['vintage']["id"],
#                     pages[j].json()['explore_vintage']['matches'][i]['vintage']["id"],
#                     pages[j].json()['explore_vintage']['matches'][i]['vintage']["id"],
#                     pages[j].json()['explore_vintage']['matches'][i]['vintage']["id"]
#                 )]
#                 results_total.append(results)
                
#     df1 = pd.DataFrame(results_total[0],columns=cols_names)
    
    
#     for k in range(1,len(results_total)):
#         df = pd.DataFrame(results_total[k],columns=cols_names)
#         df1 = pd.concat([df1,df],axis=0)
    
#     return df1

In [635]:
def getting_style(pages, cols_names):
    results_total = []
    
    for j in range(len(pages)):
        print(j)
        for i in range(len(pages[j].json()['explore_vintage']['matches'])):
            if pages[j].json()['explore_vintage']['matches'][i]['vintage']['wine']['style']!=None:
                if len(pages[j].json()['explore_vintage']['matches'][i]['vintage']['wine']['style'])>7:
                    t = pages[j].json()['explore_vintage']['matches'][i]["vintage"]
                    s = pages[j].json()['explore_vintage']['matches'][i]["vintage"]['wine']['taste']['structure']
                    results = [(
                        t["id"],
                        t['wine']['style']['varietal_name'],
                        t['wine']['style']['body'],
                        t['wine']['style']['acidity'],
                        t['wine']['style']['acidity_description'],
                        s['acidity'],
                        s['fizziness'],
                        s['intensity'],
                        s['sweetness'],
                        s['tannin']
                    )]
                    results_total.append(results)
                else:
                    h = pages[j].json()['explore_vintage']['matches'][i]["vintage"]
                    l = pages[j].json()['explore_vintage']['matches'][i]['vintage']['wine']['style']['id']
                    results = [(
                        h["id"],
                        h['wine']['style']['varietal_name'],
                        l,
                        l,
                        l,
                        l,
                        l,
                        l,
                        l,
                        l
                    )]
                    results_total.append(results)
            else:
                r = pages[j].json()['explore_vintage']['matches'][i]["vintage"]["id"]
                results = [(
                    r,
                    r,
                    r,
                    r,
                    r,
                    r,
                    r,
                    r,
                    r,
                    r
                )]
                results_total.append(results)
                
    df1 = pd.DataFrame(results_total[0],columns=cols_names)
    
    
    for k in range(1,len(results_total)):
        df = pd.DataFrame(results_total[k],columns=cols_names)
        df1 = pd.concat([df1,df],axis=0)
    
    return df1

In [636]:
%%time

style_red = getting_style(pages_red, cols_style)
style_red

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
277
278
279
280
281
282
283
284
285
286
287
288
289
290
291
292
293
294
295
296
297
298
299
300
301
302
303
304
305
306
307
308
309
310
311
312
313
314
315
316
317
318
319
320
321
322
323
324
325
326
327
328
329
330
331
332
333
334
335
336
337
338
339
340
341
342
343
344
345
346
347
348
349
350
351
352
353
354
355
356
357
358
359
360
361
362
363
364
365
366
367
368
369
370
371
372
373
374
375
376
377
378
379
380
381
382
383
384
385
386
387
388
389
390
391
392
393
394
395
396
397
398
399
400
401
402
403
404
405
406
407
408
409
410
411
412
413
414
415
416
417
418
419
420
421
422
423
424
425
426
427
428
429
430
431
432
433
434
435
436
437
438
439
440
441
442
443
444
445
446
447
448
449
450
451
452
453
454
455
456
457
458
459
460
461
462
463
464
465
466
467
468
469
470
471
472
473
474
475
476
477
478
479
480
481
482
483
484
485
486
487
488
489
490
491
492
493
494
495
496
497
498
499
500
501
502
503
504
505
506
507
508
509
510
511
512
513
514
515
516
517
518
519
520
521
522
523
524
525
526
527
528
529
530
531
532
533
534
535
536
537
538
539
540
541
542
543
544
545
546
547
548
549
550
551
552
553
554
555
556
557
558
559
560
561
562
563
564
565
566
567
568
569
570
571
572
573
574
575
576
577
578
579
580
581
582
583
584
585
586
587
588
589
590
591
592
593
594
595
596
597
598
599
600
601
602
603
604
605
606
607
608
609
610
611
612
613
614
615
616
617
618
619
620
621
622
623
624
625
626
627
628
629
630
631
632
633
634
635
636
637
638
639
640
641
642
643
644
645
646
647
648
649
650
651
652
653
654
655
656
657
658
659
660
661
662
663
664
665
666
667
668
669
670
671
672
673
674
675
676
677
678
679
680
681
682
683
684
685
686
687
688
689
690
691
692
693
694
695
696
697
698
699
700
701
702
703
704
705
706
707
708
709
710
711
712
713
714
715
716
717
718
719
720
721
722
723
724
725
726
727
728
729
730
731
732
733
734
735
736
737
738
739
740
741
742
743
744
745
746
747
748
749
750
751
752
753
754
755
756
757
758
759
760
761
762
763
764
765
766
767
768
769
770
771
772
773
774
775
776
777
778
779
780
781
782
783
784
785
786
787
788
789
790
791
792
793
794
795
796
797
798
799
800
801
802
803
804
805
806
807
808
809
810
811
812
813
814
815
816
817
818
819
820
821
822
823
824
825
826
827
828
829
830
831
832
833
834
835
836
837
838
839
840
841
842
843
844
845
846
847
848
849
850
851
852
853
854
855
856
857
858
859
860
861
862
863
864
865
866
867
868
869
870
871
872
873
874
875
876
877
878
879
880
881
882
883
884
885
886
887
888
889
890
891
892
893
894
895
896
897
898
899
900
901
902
903
904
905
906
907
908
909
910
911
912
913
914
915
916
917
918
919
920
921
922
923
924
925
926
CPU times: total: 10min 25s
Wall time: 10min 27s

,wine_id,varietal_name,body,acidity_1,acidity_description,acidity_2,fizziness,intensity,sweetness,tannin
0,1420799,Tinto de Ribera del Duero,5,3,Alta,3.699997e+00,None,3.838660e+00,1.782721e+00,3.414929e+00
0,1199830,Tinto de Ribera del Duero,5,3,Alta,3.699997e+00,None,3.838660e+00,1.782721e+00,3.414929e+00
0,1494622,Tinto de Ribera del Duero,5,3,Alta,3.699997e+00,None,3.838660e+00,1.782721e+00,3.414929e+00
0,1229417,Tinto de Ribera del Duero,5,3,Alta,3.699997e+00,None,3.838660e+00,1.782721e+00,3.414929e+00
0,87412043,Tinto de Ribera del Duero,5,3,Alta,3.673262e+00,None,3.852933e+00,1.838424e+00,3.484004e+00
...,...,...,...,...,...,...,...,...,...,...
0,165841668,Pinot noir,3,3,Alta,3.597679e+00,None,2.029888e+00,1.492777e+00,2.049501e+00
0,146488410,Pinot noir,3,3,Alta,4.023469e+00,None,2.000000e+00,1.000000e+00,2.379592e+00
0,162784956,Syrah,4,3,Alta,3.544000e+00,None,4.088000e+00,1.667333e+00,4.293334e+00
0,161457754,161457754,161457754,161457754,161457754,1.614578e+08,161457754,1.614578e+08,1.614578e+08,1.614578e+08
0,165159053,Pinot noir,3,3,Alta,3.076269e+00,None,2.267761e+00,1.089254e+00,1.907911e+00

In [501]:
len(pages_red[926].json()['explore_vintage']['matches'])

0

In [527]:
pages_red[71].json()['explore_vintage']['matches'][0]['vintage']['wine']['style']['acidity_description']

'Alta'

In [583]:
len(pages_red[137].json()['explore_vintage']['matches'])

25

In [584]:
len(pages_red[136].json()['explore_vintage']['matches'])

25

In [591]:
pages_red[137].json()['explore_vintage']['matches'][0].keys()

dict_keys(['vintage', 'price', 'prices'])

In [623]:
pages_red[137].json()['explore_vintage']['matches'][17]['vintage']['wine'].keys()

dict_keys(['id', 'name', 'seo_name', 'type_id', 'vintage_type', 'is_natural', 'region', 'winery', 'taste', 'statistics', 'style', 'has_valid_ratings'])

In [605]:
pages_red[137].json()['explore_vintage']['matches'][16]['vintage']['wine']['style']

{'id': 81,
 'seo_name': 'portuguese-douro-red',
 'regional_name': 'Portugués',
 'varietal_name': 'Tinto de Douro',
 'name': 'Douro Tinto (Portugal)',
 'image': None,
 'background_image': None,
 'description': 'Douro Red wines range in style from light and fruity to lush and smooth to dark and dense with flavors of mature dark fruit, with herbal and schist.\n\nThe wines are often and inky purple due to the thickening of the skins from the intense summer heat of the region.\n\nMost of the best made reds from the region come from the larger port houses where the skill of the winemakers go back for generations. The wines tend to be an incredible value for the time being but costs are slowly increasing due to the amazing blends coming from the area.\n\nThe first time one sees the Douro region they will always ask themselves, how can wine be made in such rugged terrain. It is also an amazingly beautiful area, with hillsides covered in terraced vineyards. Most larger winemakers have also started converting their areas into tourist destinations and wine hotels.\n\nGrapes include the Touriga Francesa, Tinta Roriz, Touriga Nacional and Tinta Barroca. Older vineyards still contain many less used vine varieties which makes their annual efforts less predictable, but allowing for unexpected surprises yielding unique, complex wines.',
 'blurb': 'Red wine from Northern Portugal',
 'interesting_facts': ['The Douro Valley is the home of Port wine.',
  'There is evidence as early as the 3rd century AD of winegrowing in the region.',
  'Temperatures in the Douro Valley often reach above 100 degrees F in the summer months. This lends to the inky color of the red wines, whose skin is thicker than cool climate grapes.'],
 'body': 5,
 'body_description': 'De mucho cuerpo',
 'acidity': 3,
 'acidity_description': 'Alta',
 'country': {'code': 'pt',
  'name': 'Portugal',
  'native_name': 'Portugal',
  'seo_name': 'portugal',
  'currency': {'code': 'EUR', 'name': 'Euros', 'prefix': '€', 'suffix': None},
  'regions_count': 91,
  'users_count': 1048706,
  'wines_count': 54425,
  'wineries_count': 5812,
  'most_used_grapes': [{'id': 67,
    'name': 'Touriga Nacional',
    'seo_name': 'touriga-nacional',
    'has_detailed_info': True,
    'wines_count': 85787},
   {'id': 69,
    'name': 'Tinta Roriz',
    'seo_name': 'tinta-roriz',
    'has_detailed_info': False,
    'wines_count': 41047},
   {'id': 68,
    'name': 'Touriga Franca',
    'seo_name': 'touriga-franca',
    'has_detailed_info': False,
    'wines_count': 33763}]},
 'wine_type_id': 1,
 'food': [{'id': 4,
   'name': 'Ternera',
   'background_image': {'location': '//images.vivino.com/backgrounds/foods/4_beef.png',
    'variations': {'small': '//images.vivino.com/backgrounds/foods/thumbs/4_beef_932x810.png'}},
   'seo_name': 'beef'},
  {'id': 5,
   'name': 'Pasta',
   'background_image': {'location': '//images.vivino.com/backgrounds/foods/5_pasta.png',
    'variations': {'small': '//images.vivino.com/backgrounds/foods/thumbs/5_pasta_932x810.png'}},
   'seo_name': None},
  {'id': 8,
   'name': 'Cordero',
   'background_image': {'location': '//images.vivino.com/backgrounds/foods/8_lamb.png',
    'variations': {'small': '//images.vivino.com/backgrounds/foods/thumbs/8_lamb_932x810.png'}},
   'seo_name': 'lamb'},
  {'id': 11,
   'name': 'Carne de caza (ciervo, carne de venado)',
   'background_image': {'location': '//images.vivino.com/backgrounds/foods/11_venison.png',
    'variations': {'small': '//images.vivino.com/backgrounds/foods/thumbs/11_venison_932x810.png'}},
   'seo_name': 'game'}],
 'grapes': [{'id': 67,
   'name': 'Touriga Nacional',
   'seo_name': 'touriga-nacional',
   'has_detailed_info': True,
   'wines_count': 85787},
  {'id': 69,
   'name': 'Tinta Roriz',
   'seo_name': 'tinta-roriz',
   'has_detailed_info': False,
   'wines_count': 41047},
  {'id': 390,
   'name': 'Touriga Francesa',
   'seo_name': 'touriga-francesa',
   'has_detailed_info': False,
   'wines_count': 3254}],
 'region': {'id': 433,
  'name': 'Douro',
  'name_en': '',
  'seo_name': 'douro',
  'country': {'code': 'pt',
   'name': 'Portugal',
   'native_name': 'Portugal',
   'seo_name': 'portugal',
   'currency': {'code': 'EUR', 'name': 'Euros', 'prefix': '€', 'suffix': None},
   'regions_count': 91,
   'users_count': 1048706,
   'wines_count': 54425,
   'wineries_count': 5812,
   'most_used_grapes': [{'id': 67,
     'name': 'Touriga Nacional',
     'seo_name': 'touriga-nacional',
     'has_detailed_info': True,
     'wines_count': 85787},
    {'id': 69,
     'name': 'Tinta Roriz',
     'seo_name': 'tinta-roriz',
     'has_detailed_info': False,
     'wines_count': 41047},
    {'id': 68,
     'name': 'Touriga Franca',
     'seo_name': 'touriga-franca',
     'has_detailed_info': False,
     'wines_count': 33763}]},
  'parent_id': 2078,
  'background_image': {'location': '//images.vivino.com/regions/backgrounds/ePk3750qR3ioS9lEfzLBnA.jpg',
   'variations': {'large': '//thumbs.vivino.com/region_backgrounds/ePk3750qR3ioS9lEfzLBnA_1280x760.jpg',
    'medium': '//thumbs.vivino.com/region_backgrounds/ePk3750qR3ioS9lEfzLBnA_600x356.jpg'}},
  'class': {'typecast_map': {'background_image': {}, 'class': {}}},
  'statistics': {'wineries_count': 1445,
   'wines_count': 7743,
   'sub_regions_count': 3,
   'parent_regions_count': 1}}}

In [348]:
len(pages_red)

927

In [344]:
pages_red[0].json()['explore_vintage']['matches'][0]['vintage']['wine']['style']['body']

5

#### RED WINES

In [500]:
style_red = getting_style(pages_red, cols_style)
style_red

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
277
278
279
280
281
282
283
284
285
286
287
288
289
290
291
292
293
294
295
296
297
298
299
300
301
302
303
304
305
306
307
308
309
310
311
312
313
314
315
316
317
318
319
320
321
322
323
324
325
326
327
328
329
330
331
332
333
334
335
336
337
338
339
340
341
342
343
344
345
346
347
348
349
350
351
352
353
354
355
356
357
358
359
360
361
362
363
364
365
366
367
368
369
370
371
372
373
374
375
376
377
378
379
380
381
382
383
384
385
386
387
388
389
390
391
392
393
394
395
396
397
398
399
400
401
402
403
404
405
406
407
408
409
410
411
412
413
414
415
416
417
418
419
420
421
422
423
424
425
426
427
428
429
430
431
432
433
434
435
436
437
438
439
440
441
442
443
444
445
446
447
448
449
450
451
452
453
454
455
456
457
458
459
460
461
462
463
464
465
466
467
468
469
470
471
472
473
474
475
476
477
478
479
480
481
482
483
484
485
486
487
488
489
490
491
492
493
494
495
496
497
498
499
500
501
502
503
504
505
506
507
508
509
510
511
512
513
514
515
516
517
518
519
520
521
522
523
524
525
526
527
528
529
530
531
532
533
534
535
536
537
538
539
540
541
542
543
544
545
546
547
548
549
550
551
552
553
554
555
556
557
558
559
560
561
562
563
564
565
566
567
568
569
570
571
572
573
574
575
576
577
578
579
580
581
582
583
584
585
586
587
588
589
590
591
592
593
594
595
596
597
598
599
600
601
602
603
604
605
606
607
608
609
610
611
612
613
614
615
616
617
618
619
620
621
622
623
624
625
626
627
628
629
630
631
632
633
634
635
636
637
638
639
640
641
642
643
644
645
646
647
648
649
650
651
652
653
654
655
656
657
658
659
660
661
662
663
664
665
666
667
668
669
670
671
672
673
674
675
676
677
678
679
680
681
682
683
684
685
686
687
688
689
690
691
692
693
694
695
696
697
698
699
700
701
702
703
704
705
706
707
708
709
710
711
712
713
714
715
716
717
718
719
720
721
722
723
724
725
726
727
728
729
730
731
732
733
734
735
736
737
738
739
740
741
742
743
744
745
746
747
748
749
750
751
752
753
754
755
756
757
758
759
760
761
762
763
764
765
766
767
768
769
770
771
772
773
774
775
776
777
778
779
780
781
782
783
784
785
786
787
788
789
790
791
792
793
794
795
796
797
798
799
800
801
802
803
804
805
806
807
808
809
810
811
812
813
814
815
816
817
818
819
820
821
822
823
824
825
826
827
828
829
830
831
832
833
834
835
836
837
838
839
840
841
842
843
844
845
846
847
848
849
850
851
852
853
854
855
856
857
858
859
860
861
862
863
864
865
866
867
868
869
870
871
872
873
874
875
876
877
878
879
880
881
882
883
884
885
886
887
888
889
890
891
892
893
894
895
896
897
898
899
900
901
902
903
904
905
906
907
908
909
910
911
912
913
914
915
916
917
918
919
920
921
922
923
924
925
926

IndexError: list index out of range

#### WHITE WINES

In [484]:
pages_white[0].json()['explore_vintage']['matches'][0]['vintage']['wine']['style']['varietal_name']

'Blanco de Rioja'

In [485]:
len(pages_white[0].json()['explore_vintage']['matches'][0]['vintage']['wine']['style'].keys())

19

In [483]:
style_white = getting_style(pages_white, cols_style)
style_white

0

TypeError: 'NoneType' object is not subscriptable

### Grapes

In [294]:
def getting_grapes(pages, cols_names):
    
    results_total = []
    
    for j in range(len(pages)):
        results = 
       
        results_total.append(results)
    
    
    df1 = pd.DataFrame(results_total[0],columns=cols_names)
    
    
    for i in range(1,len(results_total)):
        df = pd.DataFrame(results_total[i],columns=cols_names)
        df1 = pd.concat([df1,df],axis=0)
    
    return df1

#### RED WINES

In [386]:
# most_used_grapes_id
pages_red[25].json()['explore_vintage']['matches'][0]['vintage']['wine']['region']['country']['most_used_grapes'][0]['id']

19

In [335]:
# most_used_grapes_name
pages_red[0].json()['explore_vintage']['matches'][0]['vintage']['wine']['region']['country']['most_used_grapes'][0]['name']

'Tempranillo'

In [ ]:
for x in range(200,209):
    print(pages_red[x].json()['explore_vintage']['matches'][0]['vintage']['wine']['region']['country']['most_used_grapes'])
#     print(pages_red[x].json()['explore_vintage']['matches'][0]['vintage']['name'])

In [398]:
for x in range(1,9):
    print(pages_white[26].json()['explore_vintage']['matches'][x]['vintage']['wine']['region']['country']['most_used_grapes'][2]['name'])

Cabernet Sauvignon
Cabernet Sauvignon
Cabernet Sauvignon
Cabernet Sauvignon
Cabernet Sauvignon
Cabernet Sauvignon
Cabernet Sauvignon
Cabernet Sauvignon

#### WHITE WINES

In [340]:
# most_used_grapes_id
pages_white[10].json()['explore_vintage']['matches'][0]['vintage']['wine']['region']['country']['most_used_grapes'][0]['id']

19

In [482]:
# most_used_grapes_name
pages_white[0].json()['explore_vintage']['matches'][8]['vintage']['wine']['region']['country']['most_used_grapes'][0]['name']

'Tempranillo'

In [467]:
pages_white[0].json()['explore_vintage']['matches'][9]['vintage']['wine']['style']['varietal_name']

'Albariño'

# Wine

In [25]:
data = results['explore_vintage']['matches']

In [26]:
# wine_id
data[0]['vintage']['id']

163714281

In [27]:
# wine_name
data[0]['vintage']['name']

'Ayuso Abadia del Roble Tinto 2020'

In [28]:
# winery_name
data[0]['vintage']['wine']['winery']['name']

'Ayuso'

In [124]:
# wine_type: 1=red 2=white 3=cava 4=rosado 
data[0]['vintage']['wine']['type_id']

1

In [30]:
# wine_region
data[0]['vintage']['wine']['region']['name']

'La Mancha'

In [31]:
data[0]['vintage']['wine']['region']['country']['seo_name']

'spain'

In [32]:
# wine_year
data[0]['vintage']['year']

2020

In [33]:
# wine_ratings
data[0]['vintage']['statistics']['wine_ratings_count']

3585

In [34]:
# wine_rates
data[0]['vintage']['statistics']['wine_ratings_average']

2.9

In [125]:
results1 = [
    (
        t["vintage"]["id"],
        t["vintage"]["name"],
        t['vintage']['wine']['winery']['name'],
        t['vintage']['wine']['type_id'],
        t['vintage']['wine']['region']['name'],
        t['vintage']['wine']['region']['country']['seo_name'],
        t['vintage']['year'],
        t['vintage']['statistics']['wine_ratings_count'],
        t['vintage']['statistics']['wine_ratings_average']
    )
    for t in data
]
wine = pd.DataFrame(results1,columns=['wine_id','wine_name','winery','type','region','country','year','num_ratings','rate'])

wine

,wine_id,wine_name,winery,type,region,country,year,num_ratings,rate
0,163714281,Ayuso Abadia del Roble Tinto 2020,Ayuso,1,La Mancha,spain,2020,3585,2.9
1,163421900,Bodega Rochal Calixto Rufete 2019,Bodega Rochal,1,Sierra de Salamanca,spain,2019,248,3.3
2,160093475,Cata Regia Crianza 2018,Cata Regia,1,Terra Alta,spain,2018,534,3.5
3,143481585,Marqués de la Concordia MM Tinto Crianza 2015,Marqués de la Concordia,1,Cataluña,spain,2015,278,3.2
4,162886140,Antaño Rioja Tempranillo 2020,Antaño,1,Rioja,spain,2020,14721,3.3
5,163259267,Navajas Garnacha 2018,Navajas,1,Rioja,spain,2018,68,3.4
6,156761867,Canforrales Clásico Tempranillo 2018,Canforrales,1,La Mancha,spain,2018,1191,3.4
7,157445951,Don Diego Escolano Reserva 2016,Don Diego Escolano,1,Cariñena,spain,2016,162,3.3
8,163225367,Osborne Solaz Tempranillo 2020,Osborne,1,Castilla,spain,2020,2034,3.4
9,159935140,Las Campanas Tempranillo 2018,Las Campanas,1,Navarra,spain,2018,156,3.4
10,157649103,Gran Feudo 626 Barricas Edición Limitada Crian...,Gran Feudo,1,Navarra,spain,2017,302,3.3
11,163087313,Osborne Solaz Tempranillo - Cabernet Sauvignon...,Osborne,1,Castilla,spain,2020,8499,3.4
12,167181804,El Circo Arlequín Syrah 2020,El Circo,1,Cariñena,spain,2020,1038,3.4
13,156933146,Enate Tapas Tempranillo 2018,Enate,1,Somontano,spain,2018,2334,3.3
14,166714267,Los Hermanos Manzanos Tempranillo 2020,Los Hermanos Manzanos,1,Rioja,spain,2020,983,3.6
15,163804482,El Circo Volatinero Tempranillo 2020,El Circo,1,Cariñena,spain,2020,4555,3.5
16,159375239,Félix Solís Casa Albali Tempranillo - Shiraz 2019,Félix Solís,1,Valdepeñas,spain,2019,2105,3.5
17,159565710,Reserva de la Tierra Pago de Pelde Syrah - Tem...,Reserva de la Tierra,1,Terra Alta,spain,2017,141,3.8
18,11231853,Félix Solís Casa Albali Crianza 2012,Félix Solís,1,Valdepeñas,spain,2012,234,3.2
19,156872483,Hoya de Cadenas Reserva Tempranillo 2018,Hoya de Cadenas,1,Utiel-Requena,spain,2018,8440,3.4
20,163019597,Bach Viña Extrísima Tinto 2020,Bach,1,Cataluña,spain,2020,3281,3.2
21,163437312,Ca N'Estella Clot Dels Oms Petit Tinto 2019,Ca N'Estella,1,Penedès,spain,2019,762,3.1
22,168355423,Nuviana Tinto 2021,Nuviana,1,Valle del Cinca,spain,2021,1349,3.1
23,150341712,Ayuso Estola Crianza 2017,Ayuso,1,La Mancha,spain,2017,2207,3.2
24,163373075,Bodegas Aragonesas Coto de Hayas Tempranillo -...,Bodegas Aragonesas,1,Campo de Borja,spain,2020,3724,3.4

### Purchase

In [36]:
# wine_price
data[0]['price']['amount']

2.41

In [37]:
# wine_currency
data[0]['price']['currency']['code']

'EUR'

In [38]:
# wine_bottle_type_id
data[0]['price']['bottle_type']['id']

1

In [39]:
# wine_bottle_type_short_name
data[0]['price']['bottle_type']['short_name']

'botella'

In [40]:
# wine_bottle_type_volume_ml
data[0]['price']['bottle_type']['volume_ml']

750

In [41]:
results2 = [
    (
        t["vintage"]["id"],
        t['price']['amount'],
        t['price']['bottle_type']['id'],
        t['price']['bottle_type']['short_name'],
        t['price']['bottle_type']['volume_ml']
    )
    for t in data
]
purchase = pd.DataFrame(results2,columns=['wine_id','price_euros','bottle_type_id','bottle_type','vol_ml'])

purchase

      wine_id  price currency  bottle_type_id   bottle_type  vol_ml
0   163714281   2.41      EUR               1       botella     750
1   163421900   2.98      EUR               1       botella     750
2   160093475   2.99      EUR               1       botella     750
3   143481585   3.00      EUR               1       botella     750
4   162886140   3.20      EUR               1       botella     750
5   163259267   3.45      EUR               1       botella     750
6   156761867   3.50      EUR               1       botella     750
7   157445951   3.51      EUR               1       botella     750
8   163225367   3.57      EUR               1       botella     750
9   159935140   3.61      EUR               1       botella     750
10  157649103   3.62      EUR               3  botella de ½     375
11  163087313   3.69      EUR               1       botella     750
12  167181804   3.75      EUR               1       botella     750
13  156933146   3.78      EUR               1       botella     750
14  166714267   3.79      EUR               1       botella     750
15  163804482   3.90      EUR               1       botella     750
16  159375239   3.95      EUR               1       botella     750
17  159565710   3.99      EUR               1       botella     750
18   11231853   3.99      EUR               1       botella     750
19  156872483   3.99      EUR               1       botella     750
20  163019597   4.00      EUR               1       botella     750
21  163437312   4.00      EUR               1       botella     750
22  168355423   4.01      EUR               1       botella     750
23  150341712   4.03      EUR               1       botella     750
24  163373075   4.10      EUR               1       botella     750

### Grapes

In [42]:
# most_used_grapes_dictionaries
data[0]['vintage']['wine']['region']['country']['most_used_grapes']

[{'id': 19,
  'name': 'Tempranillo',
  'seo_name': 'tempranillo',
  'has_detailed_info': True,
  'wines_count': 172842},
 {'id': 142,
  'name': 'Garnacha',
  'seo_name': 'garnacha',
  'has_detailed_info': True,
  'wines_count': 58111},
 {'id': 2,
  'name': 'Cabernet Sauvignon',
  'seo_name': 'cabernet-sauvignon',
  'has_detailed_info': True,
  'wines_count': 801751}]

In [43]:
# most_used_grapes_dictionaries (length change in every wine)
len(data[0]['vintage']['wine']['region']['country']['most_used_grapes'])

3

In [44]:
# most_used_grapes_dictionaries 1
data[0]['vintage']['wine']['region']['country']['most_used_grapes'][0]

{'id': 19,
 'name': 'Tempranillo',
 'seo_name': 'tempranillo',
 'has_detailed_info': True,
 'wines_count': 172842}

In [45]:
# most_used_grapes_dictionaries 2
data[0]['vintage']['wine']['region']['country']['most_used_grapes'][1]

{'id': 142,
 'name': 'Garnacha',
 'seo_name': 'garnacha',
 'has_detailed_info': True,
 'wines_count': 58111}

In [46]:
# most_used_grapes_dictionaries 3
data[0]['vintage']['wine']['region']['country']['most_used_grapes'][2]

{'id': 2,
 'name': 'Cabernet Sauvignon',
 'seo_name': 'cabernet-sauvignon',
 'has_detailed_info': True,
 'wines_count': 801751}

#### usefull parts

In [47]:
# most_used_grapes_id
data[0]['vintage']['wine']['region']['country']['most_used_grapes'][0]['id']

19

In [48]:
# most_used_grapes_name
data[0]['vintage']['wine']['region']['country']['most_used_grapes'][0]['name']

'Tempranillo'

In [101]:
# getting data from grapes
wine_id = []
wine_id.append(data[0]['vintage']['id'])

grape_id = []
grapes = []

for i in range(len(data[0]['vintage']['wine']['region']['country']['most_used_grapes'])):
    grape_id.append(data[0]['vintage']['wine']['region']['country']['most_used_grapes'][i]['id'])
    grapes.append(data[0]['vintage']['wine']['region']['country']['most_used_grapes'][i]['name'])
    
df = pd.DataFrame(grape_id,grapes).reset_index(drop = False)
df['wine_id'] = wine_id*df.shape[0]
df.columns = ['grape','grape_id','wine_id']
df

                grape  grape_id    wine_id
0         Tempranillo        19  163714281
1            Garnacha       142  163714281
2  Cabernet Sauvignon         2  163714281

In [72]:
results3 = [
    (
        [data[0]['vintage']['wine']['region']['country']['most_used_grapes'][i]['id'] for i in range(len(data[0]['vintage']['wine']['region']['country']['most_used_grapes']))]
    )for t in data]
grapes = pd.DataFrame(results3,columns=['wine_id','grape_id','grape_name'])

grapes

In [70]:
[data[0]['vintage']['wine']['region']['country']['most_used_grapes'][i]['id'] for i in range(len(data[0]['vintage']['wine']['region']['country']['most_used_grapes']))]

[19, 142, 2]

In [77]:
[data[0]['vintage']['wine']['region']['country']['most_used_grapes'][i]['name'] for i in range(len(data[0]['vintage']['wine']['region']['country']['most_used_grapes']))]

['Tempranillo', 'Garnacha', 'Cabernet Sauvignon']

In [ ]:
results = response.json()

### Style & Taste

In [50]:
# style_body
data[0]['vintage']['wine']['style']['body']

4

In [51]:
# style_acidity
data[0]['vintage']['wine']['style']['acidity']

2

In [52]:
# taste_structure
data[0]['vintage']['wine']['taste']['structure']

{'acidity': 2.9226007,
 'fizziness': None,
 'intensity': 3.81,
 'sweetness': 1.6557305,
 'tannin': 3.2921908,
 'user_structure_count': 90,
 'calculated_structure_count': 49}

In [53]:
# taste_acidity
data[0]['vintage']['wine']['taste']['structure']['acidity']

2.9226007

In [54]:
# taste_fizziness
data[0]['vintage']['wine']['taste']['structure']['fizziness']

In [55]:
# taste_intensity
data[0]['vintage']['wine']['taste']['structure']['intensity']

3.81

In [56]:
# taste_sweetness
data[0]['vintage']['wine']['taste']['structure']['sweetness']

1.6557305

In [57]:
# taste_tannin
data[0]['vintage']['wine']['taste']['structure']['tannin']

3.2921908

In [58]:
results4 = [
    (
        t["vintage"]["id"],
        t['vintage']['wine']['style']['body'],
        t['vintage']['wine']['style']['acidity'],
        t['vintage']['wine']['taste']['structure']['acidity'],
        t['vintage']['wine']['taste']['structure']['fizziness'],
        t['vintage']['wine']['taste']['structure']['intensity'],
        t['vintage']['wine']['taste']['structure']['sweetness'],
        t['vintage']['wine']['taste']['structure']['tannin']

    )
    for t in data
]
style = pd.DataFrame(results4,columns=['wine_id','body','acidity_1','acidity_2','fizziness','intensity','sweetness','tannin'])

style

,wine_id,body,acidity_1,acidity_2,fizziness,intensity,sweetness,tannin
0,163714281,4,2,2.922601,None,3.810000,1.655730,3.292191
1,163421900,4,3,3.339466,None,3.246756,2.020355,3.062933
2,160093475,5,3,2.828437,None,3.973839,1.655580,2.927009
3,143481585,4,3,3.266678,None,3.531441,1.990018,3.230158
4,162886140,4,3,3.766680,None,3.537417,1.559733,3.647492
5,163259267,4,3,3.657876,None,3.786549,1.761858,3.968319
6,156761867,4,2,2.799259,None,3.969293,1.495572,3.589310
7,157445951,4,3,2.521321,None,3.119906,1.968915,2.711556
8,163225367,4,2,3.017252,None,3.703730,2.130266,3.216361
9,159935140,4,2,3.129613,None,3.842452,1.434710,3.530064
10,157649103,4,3,2.829421,None,3.366524,1.685970,3.363023
11,163087313,4,3,3.139123,None,3.787226,1.853632,2.917258
12,167181804,4,3,2.942395,None,3.627184,1.784919,3.685469
13,156933146,4,2,2.786923,None,3.948361,1.537826,3.619777
14,166714267,4,3,3.791350,None,3.927675,1.518769,3.914391
15,163804482,4,2,2.876396,None,4.061829,1.732586,3.649357
16,159375239,4,3,2.979029,None,3.748777,1.707140,2.744173
17,159565710,4,3,2.916829,None,3.639512,2.666585,3.055854
18,11231853,4,2,2.412017,None,4.218319,1.366134,3.581092
19,156872483,4,2,2.807049,None,4.065002,1.535943,3.343405
20,163019597,4,3,3.051992,None,3.633224,1.605641,2.959966
21,163437312,4,3,3.218373,None,3.541192,1.535596,2.788064
22,168355423,4,3,3.065768,None,3.246552,1.888458,3.114227
23,150341712,4,2,2.817932,None,3.669692,1.397522,3.633006
24,163373075,4,3,3.143396,None,3.653160,1.924041,2.836045

#### TASTE FLAVOR

In [60]:
# taste_flavor (length changes in every wine)
len(data[0]['vintage']['wine']['taste']['flavor'])

10

In [61]:
# taste_flavor 
data[0]['vintage']['wine']['taste']['flavor'][5]

{'group': 'earth',
 'stats': {'count': 3, 'score': 300},
 'primary_keywords': [{'id': 156, 'name': 'earthy', 'count': 2},
  {'id': 218, 'name': 'honey', 'count': 1}]}

In [62]:
# taste_flavor
data[0]['vintage']['wine']['taste']['flavor'][0].keys()

dict_keys(['group', 'stats', 'primary_keywords', 'secondary_keywords'])

In [63]:
# taste_flavor_group
data[0]['vintage']['wine']['taste']['flavor'][3]

{'group': 'non_oak',
 'stats': {'count': 6, 'score': 270},
 'primary_keywords': [{'id': 98, 'name': 'chestnut', 'count': 1},
  {'id': 291, 'name': 'nutty', 'count': 1}],
 'secondary_keywords': [{'id': 105, 'name': 'cinnamon', 'count': 3},
  {'id': 117, 'name': 'coffee', 'count': 1},
  {'id': 434, 'name': 'vanilla', 'count': 1}]}

In [64]:
# taste_flavor_stats
data[0]['vintage']['wine']['taste']['flavor'][0]['stats']

{'count': 15, 'score': 2732}

In [65]:
# taste_flavor_1st keyword
data[0]['vintage']['wine']['taste']['flavor'][0]['primary_keywords']

[{'id': 348, 'name': 'raspberry', 'count': 10},
 {'id': 93, 'name': 'cherry', 'count': 7},
 {'id': 354, 'name': 'red fruit', 'count': 7},
 {'id': 400, 'name': 'strawberry', 'count': 3}]

In [66]:
# taste_flavor_2nd keyword
data[0]['vintage']['wine']['taste']['flavor'][0]['secondary_keywords']

[{'id': 229, 'name': 'jam', 'count': 2}]

In [69]:
for i in range(len(data[0]['vintage']['wine']['taste']['flavor'])):
    try:
        print('group ', data[0]['vintage']['wine']['taste']['flavor'][i]['group'])
        for j in range(len(data[0]['vintage']['wine']['taste']['flavor'][0]['primary_keywords'])):
            print('prim ',data[0]['vintage']['wine']['taste']['flavor'][i]['primary_keywords'][j]['id'],'_',data[0]['vintage']['wine']['taste']['flavor'][i]['primary_keywords'][j]['name'])

        for k in range(len(data[0]['vintage']['wine']['taste']['flavor'][i]['secondary_keywords'])):
            print('sec ',data[0]['vintage']['wine']['taste']['flavor'][i]['secondary_keywords'][k]['id'],'_',data[0]['vintage']['wine']['taste']['flavor'][i]['secondary_keywords'][k]['name'])

    except:
        print('NA')

group  red_fruit
prim  348 _ raspberry
prim  93 _ cherry
prim  354 _ red fruit
prim  400 _ strawberry
sec  229 _ jam
group  oak
prim  292 _ oak
prim  117 _ coffee
prim  434 _ vanilla
NA
group  black_fruit
prim  334 _ plum
prim  229 _ jam
prim  53 _ blackcurrant jam
prim  470 _ cassis
NA
group  non_oak
prim  98 _ chestnut
prim  291 _ nutty
NA
group  spices
prim  105 _ cinnamon
prim  416 _ thyme
NA
group  earth
prim  156 _ earthy
prim  218 _ honey
NA
group  dried_fruit
prim  347 _ raisin
NA
group  citrus_fruit
prim  252 _ lime
NA
group  microbio
prim  91 _ cheese
NA
group  tree_fruit
prim  11 _ apricot
NA

In [ ]:
results5 = [
    (
        t["vintage"]["id"],
        t['vintage']['wine']['style']['body'],
        t['vintage']['wine']['style']['acidity'],
        t['vintage']['wine']['taste']['structure']['acidity'],
        t['vintage']['wine']['taste']['structure']['fizziness'],
        t['vintage']['wine']['taste']['structure']['intensity'],
        t['vintage']['wine']['taste']['structure']['sweetness'],
        t['vintage']['wine']['taste']['structure']['tannin']

    )
    for t in data
]
taste_flavor = pd.DataFrame(results4,columns=[''])

taste_flavor

In [502]:
# alcohol :(
data[0]['vintage']['wine']

{'id': 2084964,
 'name': 'Abadia del Roble Tinto',
 'seo_name': 'abadia-del-roble-tinto',
 'type_id': 1,
 'vintage_type': 0,
 'is_natural': False,
 'region': {'id': 1761,
  'name': 'La Mancha',
  'name_en': '',
  'seo_name': 'la-mancha',
  'country': {'code': 'es',
   'name': 'España',
   'native_name': 'España',
   'seo_name': 'spain',
   'currency': {'code': 'EUR', 'name': 'Euros', 'prefix': '€', 'suffix': None},
   'regions_count': 152,
   'users_count': 2150276,
   'wines_count': 138292,
   'wineries_count': 17952,
   'most_used_grapes': [{'id': 19,
     'name': 'Tempranillo',
     'seo_name': 'tempranillo',
     'has_detailed_info': True,
     'wines_count': 172842},
    {'id': 142,
     'name': 'Garnacha',
     'seo_name': 'garnacha',
     'has_detailed_info': True,
     'wines_count': 58111},
    {'id': 2,
     'name': 'Cabernet Sauvignon',
     'seo_name': 'cabernet-sauvignon',
     'has_detailed_info': True,
     'wines_count': 801751}]},
  'class': {'typecast_map': {'background_image': {}, 'class': {}}},
  'background_image': {'location': '//images.vivino.com/regions/backgrounds/CRo_etP7SKOdubm1z-TkoQ.jpg',
   'variations': {'large': '//thumbs.vivino.com/region_backgrounds/CRo_etP7SKOdubm1z-TkoQ_1280x760.jpg',
    'medium': '//thumbs.vivino.com/region_backgrounds/CRo_etP7SKOdubm1z-TkoQ_600x356.jpg'}}},
 'winery': {'id': 13339,
  'name': 'Ayuso',
  'seo_name': 'ayuso',
  'status': 0,
  'background_image': None},
 'taste': {'structure': {'acidity': 2.9226007,
   'fizziness': None,
   'intensity': 3.81,
   'sweetness': 1.6557305,
   'tannin': 3.2921908,
   'user_structure_count': 90,
   'calculated_structure_count': 49},
  'flavor': [{'group': 'red_fruit',
    'stats': {'count': 15, 'score': 2732},
    'primary_keywords': [{'id': 348, 'name': 'raspberry', 'count': 10},
     {'id': 93, 'name': 'cherry', 'count': 7},
     {'id': 354, 'name': 'red fruit', 'count': 7},
     {'id': 400, 'name': 'strawberry', 'count': 3}],
    'secondary_keywords': [{'id': 229, 'name': 'jam', 'count': 2}]},
   {'group': 'oak',
    'stats': {'count': 10, 'score': 1071},
    'primary_keywords': [{'id': 292, 'name': 'oak', 'count': 8},
     {'id': 117, 'name': 'coffee', 'count': 1},
     {'id': 434, 'name': 'vanilla', 'count': 1}],
    'secondary_keywords': [{'id': 105, 'name': 'cinnamon', 'count': 3}]},
   {'group': 'black_fruit',
    'stats': {'count': 7, 'score': 836},
    'primary_keywords': [{'id': 334, 'name': 'plum', 'count': 5},
     {'id': 229, 'name': 'jam', 'count': 2},
     {'id': 53, 'name': 'blackcurrant jam', 'count': 1},
     {'id': 470, 'name': 'cassis', 'count': 1}]},
   {'group': 'non_oak',
    'stats': {'count': 6, 'score': 270},
    'primary_keywords': [{'id': 98, 'name': 'chestnut', 'count': 1},
     {'id': 291, 'name': 'nutty', 'count': 1}],
    'secondary_keywords': [{'id': 105, 'name': 'cinnamon', 'count': 3},
     {'id': 117, 'name': 'coffee', 'count': 1},
     {'id': 434, 'name': 'vanilla', 'count': 1}]},
   {'group': 'spices',
    'stats': {'count': 3, 'score': 259},
    'primary_keywords': [{'id': 105, 'name': 'cinnamon', 'count': 3},
     {'id': 416, 'name': 'thyme', 'count': 1}],
    'secondary_keywords': [{'id': 434, 'name': 'vanilla', 'count': 1}]},
   {'group': 'earth',
    'stats': {'count': 3, 'score': 300},
    'primary_keywords': [{'id': 156, 'name': 'earthy', 'count': 2},
     {'id': 218, 'name': 'honey', 'count': 1}]},
   {'group': 'dried_fruit',
    'stats': {'count': 2, 'score': 132},
    'primary_keywords': [{'id': 347, 'name': 'raisin', 'count': 1}],
    'secondary_keywords': [{'id': 229, 'name': 'jam', 'count': 2}]},
   {'group': 'citrus_fruit',
    'stats': {'count': 1, 'score': 100},
    'primary_keywords': [{'id': 252, 'name': 'lime', 'count': 1}]},
   {'group': 'microbio',
    'stats': {'count': 1, 'score': 100},
    'primary_keywords': [{'id': 91, 'name': 'cheese', 'count': 1}]},
   {'group': 'tree_fruit',
    'stats': {'count': 1, 'score': 100},
    'primary_keywords': [{'id': 11, 'name': 'apricot', 'count': 1}]}]},
 'statistics': {'status': 'Normal',
  'ratings_count': 3585,
  'ratings_average': 2.9,
  'labels_count': 33138,
  'vintages_count': 35},
 'style': {'id': 304,
  'seo_name': 'spanish-tempranillo',
  'regional_name': 'Español',
  'varietal_name': 'Tempranillo',
  'name': 'Tempranillo (España)',
  'image': None,
  'background_image': None,
  'description': None,
  'blurb': None,
  'interesting_facts': None,
  'body': 4,
  'body_description': 'De mucho cuerpo',
  'acidity': 2,
  'acidity_description': 'Media',
  'country': {'code': 'es',
   'name': 'España',
   'native_name': 'España',
   'seo_name': 'spain',
   'currency': {'code': 'EUR', 'name': 'Euros', 'prefix': '€', 'suffix': None},
   'regions_count': 152,
   'users_count': 2150276,
   'wines_count': 138292,
   'wineries_count': 17952,
   'most_used_grapes': [{'id': 19,
     'name': 'Tempranillo',
     'seo_name': 'tempranillo',
     'has_detailed_info': True,
     'wines_count': 172842},
    {'id': 142,
     'name': 'Garnacha',
     'seo_name': 'garnacha',
     'has_detailed_info': True,
     'wines_count': 58111},
    {'id': 2,
     'name': 'Cabernet Sauvignon',
     'seo_name': 'cabernet-sauvignon',
     'has_detailed_info': True,
     'wines_count': 801751}]},
  'wine_type_id': 1,
  'food': [{'id': 4,
    'name': 'Ternera',
    'background_image': {'location': '//images.vivino.com/backgrounds/foods/4_beef.png',
     'variations': {'small': '//images.vivino.com/backgrounds/foods/thumbs/4_beef_932x810.png'}},
    'seo_name': 'beef'},
   {'id': 8,
    'name': 'Cordero',
    'background_image': {'location': '//images.vivino.com/backgrounds/foods/8_lamb.png',
     'variations': {'small': '//images.vivino.com/backgrounds/foods/thumbs/8_lamb_932x810.png'}},
    'seo_name': 'lamb'},
   {'id': 9,
    'name': 'Ternera lechal',
    'background_image': {'location': '//images.vivino.com/backgrounds/foods/9_veal.png',
     'variations': {'small': '//images.vivino.com/backgrounds/foods/thumbs/9_veal_932x810.png'}},
    'seo_name': 'veal'},
   {'id': 20,
    'name': 'Aves',
    'background_image': {'location': '//images.vivino.com/backgrounds/foods/20_chicken.png',
     'variations': {'small': '//images.vivino.com/backgrounds/foods/thumbs/20_chicken_932x810.png'}},
    'seo_name': 'poultry'}],
  'grapes': [{'id': 19,
    'name': 'Tempranillo',
    'seo_name': 'tempranillo',
    'has_detailed_info': True,
    'wines_count': 172842}],
  'region': {'id': 1707,
   'name': 'Bajo Aragón',
   'name_en': '',
   'seo_name': 'bajo-aragon',
   'country': {'code': 'es',
    'name': 'España',
    'native_name': 'España',
    'seo_name': 'spain',
    'currency': {'code': 'EUR',
     'name': 'Euros',
     'prefix': '€',
     'suffix': None},
    'regions_count': 152,
    'users_count': 2150276,
    'wines_count': 138292,
    'wineries_count': 17952,
    'most_used_grapes': [{'id': 19,
      'name': 'Tempranillo',
      'seo_name': 'tempranillo',
      'has_detailed_info': True,
      'wines_count': 172842},
     {'id': 142,
      'name': 'Garnacha',
      'seo_name': 'garnacha',
      'has_detailed_info': True,
      'wines_count': 58111},
     {'id': 2,
      'name': 'Cabernet Sauvignon',
      'seo_name': 'cabernet-sauvignon',
      'has_detailed_info': True,
      'wines_count': 801751}]},
   'parent_id': 465,
   'background_image': None,
   'class': {'typecast_map': {'background_image': {}, 'class': {}}},
   'statistics': {'wineries_count': 20,
    'wines_count': 138,
    'sub_regions_count': 0,
    'parent_regions_count': 1}}},
 'has_valid_ratings': True}