# Import libraries and data

In [1]:
import pandas as pd
import numpy as np
pd.set_option('display.max_columns', None)

In [2]:
import pymysql
from sqlalchemy import create_engine
import getpass 
password = getpass.getpass()

········

In [3]:
connection_string = 'mysql+pymysql://root:' + password + '@localhost/clean_winery'
engine = create_engine(connection_string)

## Getting all the data

In [4]:
query = ''' SELECT d.wine_id, d.type, d.wine_name, d.country, w.region, d.varietal_name, w.winery, w.year, d.style_id, d.body, s.body_description, d.acidity_1, s.acidity_description, d.acidity_2, d.fizziness, d.intensity, d.sweetness, d.tannin, p.vol_ml, p.price_eur, w.num_ratings, w.rate FROM to_clean d
LEFT JOIN wine w USING (wine_id)
LEFT JOIN purchase p USING (wine_id)
LEFT JOIN style s USING (wine_id);'''

all_data = pd.read_sql(query, engine)

In [5]:
all_data.shape

(21076, 22)

In [6]:
all_data.duplicated(subset = 'wine_id').sum()

667

In [7]:
all_data['varietal_name'].value_counts()

Blanco                     4124
Tinto                      2934
Riesling                    960
Tinto de Douro              741
Chardonnay                  688
                           ...
Malbec - Syrah                2
Chasselas                     1
Merlot - Syrah                1
Dornfelder                    1
Chenin blanc - Viognier       1
Name: varietal_name, Length: 117, dtype: int64

In [8]:
all_data['varietal_name'] = np.where(all_data['varietal_name'].isin(['Muscat','Muscadet', 'Moscatel - Chardonnay']),'Moscatel',all_data['varietal_name'])

In [9]:
all_data['varietal_name'] = np.where(all_data['varietal_name'].isin(['Pinot noir']),'Pinot Noir',all_data['varietal_name'])

In [10]:
all_data['varietal_name'] = np.where(all_data['varietal_name'].isin(['Petite Sirah']),'Syrah',all_data['varietal_name'])

In [11]:
all_data['varietal_name'] = np.where(all_data['varietal_name'].isin(['Pinot gris']),'Pinot Gris',all_data['varietal_name'])

In [12]:
all_data['varietal_name'] = np.where(all_data['varietal_name'].isin(['Pinot blanc']),'Pinot Blanc',all_data['varietal_name'])

In [13]:
all_data['varietal_name'] = np.where(all_data['varietal_name'].isin(['Blend blanco']),'Blanco',all_data['varietal_name'])

In [14]:
all_data['varietal_name'] = np.where(all_data['varietal_name'].isin(['Blend tinto']),'Tinto',all_data['varietal_name'])

#### changing the combinations of varietal types, to the first one

In [15]:
all_data['varietal_name'] = np.where(all_data['varietal_name'].isin(['Sauvignon Blanc - Muscat']),'Sauvignon Blanc',all_data['varietal_name'])

In [16]:
all_data['varietal_name'] = np.where(all_data['varietal_name'].isin(['Malbec - Syrah']),'Malbec',all_data['varietal_name'])

In [17]:
all_data['varietal_name'] = np.where(all_data['varietal_name'].isin(['Torrontés - Riesling']),'Torrontés',all_data['varietal_name'])

In [18]:
all_data['varietal_name'] = np.where(all_data['varietal_name'].isin(['Chardonnay - Pinot Noir']),'Chardonnay',all_data['varietal_name'])

In [19]:
all_data['varietal_name'] = np.where(all_data['varietal_name'].isin(['Cabernet - Syrah']),'Cabernet',all_data['varietal_name'])

In [20]:
all_data['varietal_name'] = np.where(all_data['varietal_name'].isin(['Syrah - Viognier']),'Syrah',all_data['varietal_name'])

In [21]:
all_data['varietal_name'] = np.where(all_data['varietal_name'].isin(['Cabernet - Malbec']),'Cabernet',all_data['varietal_name'])

In [22]:
all_data['varietal_name'] = np.where(all_data['varietal_name'].isin(['Merlot - Syrah']),'Merlot',all_data['varietal_name'])

In [23]:
all_data['varietal_name'] = np.where(all_data['varietal_name'].isin(['Chenin blanc - Viognier']),'Chenin blanc',all_data['varietal_name'])

In [24]:
all_data['varietal_name'] = np.where(all_data['varietal_name'].isin(['Cabernet - Shiraz']),'Cabernet',all_data['varietal_name'])

In [25]:
all_data['varietal_name'] = np.where(all_data['varietal_name'].isin(['Sauvignon blanc']),'Sauvignon Blanc',all_data['varietal_name'])

In [26]:
all_data['varietal_name'] = np.where(all_data['varietal_name'].isin(['Blend de Pinotage']),'Pinotage',all_data['varietal_name'])

In [27]:
all_data['varietal_name'] = np.where(all_data['varietal_name'].isin(['ALbariño']),'Albariño',all_data['varietal_name'])

In [28]:
all_data['varietal_name'] = np.where(all_data['varietal_name'].isin(['Blanco de Côte Chalonnaise','Tinto de Côte Chalonnaise']),'Cote Chalonnaise',all_data['varietal_name'])

In [29]:
all_data['varietal_name'] = np.where(all_data['varietal_name'].isin(['Blanco de Côte de Beaune','Tinto de Côte de Beaune']),'Cote Beaune',all_data['varietal_name'])

In [30]:
all_data['varietal_name'] = np.where(all_data['varietal_name'].isin(['Blanco de Côte de Nuits','Tinto de Côte de Nuits']),'Cote Nuits',all_data['varietal_name'])

In [31]:
all_data['varietal_name'] = np.where(all_data['varietal_name'].isin(['Blanco de Rioja','Tinto de Rioja']),'Rioja',all_data['varietal_name'])

In [32]:
all_data['varietal_name'] = np.where(all_data['varietal_name'].isin(['Tinto de Graves']),'Tinto',all_data['varietal_name'])

In [33]:
all_data['varietal_name'] = np.where(all_data['varietal_name'].isin(['Tinto de Valpolicella']),'Tinto',all_data['varietal_name'])

In [34]:
all_data.groupby(['varietal_name']).agg({'wine_id':pd.Series.nunique}).reset_index().sort_values(by = 'wine_id',ascending=False).tail(30)

                   varietal_name  wine_id
17                     Carménère       47
36                     Hermitage       46
29                    Côte-Rotie       41
44                      Moscatel       40
90                      Viognier       33
42                    Monastrell       33
61                 Saint-Estèphe       32
31                          Gavi       32
62                  Saint-Joseph       26
43       Montepulciano d'Abruzzo       26
84                     Torrontés       25
26              Cote Chalonnaise       25
46                Müller Thurgau       22
28              Crozes-Hermitage       21
64                   Saint-Péray       17
11                       Bonarda       15
69                      Silvaner       12
85                    Treixadura       12
60                       Ripasso       11
88  Vino Nobile di Montepulciano       11
24                        Cornas        9
16                      Cannonau        8
79             Tinto de Libourne        7
49                 Pedro Ximenez        7
66                    Sangiovese        6
89                 Vino espumoso        4
87                     Vin Jaune        2
37                         Jerez        2
20                     Chasselas        1
30                    Dornfelder        1

## Encoding acidity and description, just in case

In [35]:
all_data['acidity_description'].value_counts()

Alta     16084
Media     1844
Baja       243
216          3
136          2
55           1
131          1
Name: acidity_description, dtype: int64

In [36]:
all_data['acidity_description'] = all_data['acidity_description'].map({'Alta':'High', 'Media':'Medium', 'Baja':'Low'})

In [37]:
all_data['acidity_description'].value_counts()

High      16084
Medium     1844
Low         243
Name: acidity_description, dtype: int64

In [38]:
all_data['body_description'].value_counts()

De mucho cuerpo       11527
De cuerpo medio        4709
De poco cuerpo         1780
De muy poco cuerpo      155
216                       3
136                       2
55                        1
131                       1
Name: body_description, dtype: int64

In [39]:
all_data['body_description'] = all_data['body_description'].map({'De mucho cuerpo':'High', 'De cuerpo medio':'Medium', 'De poco cuerpo':'Low','De muy poco cuerpo':'Very low'})

In [40]:
all_data['body_description'].value_counts()

High        11527
Medium       4709
Low          1780
Very low      155
Name: body_description, dtype: int64

## Again checking and cleaning region and varietal name columns

In [42]:
all_data['region'].value_counts()

Douro                             975
Stellenbosch                      706
Rioja                             653
Ribera del Duero                  563
Pfalz                             436
                                 ...
Ribbon Ridge                        1
Bottelary                           1
Alsace Grand Cru "Pfersigberg"      1
Alsace Grand Cru "Sporen"           1
Istria                              1
Name: region, Length: 1014, dtype: int64

In [43]:
all_data['varietal_name'] = np.where(all_data['varietal_name'].isin(['Tinto de Alentejo','Tinto de Douro','Tinto de Montsant','Tinto de Dão','Tinto de Priorat','Tinto de Ribera del Duero','Tinto de Toro','Tinto de Châteauneuf-du-Pape']),'Tinto',all_data['varietal_name'])

In [44]:
all_data['varietal_name'].value_counts()

Tinto            5252
Blanco           4130
Riesling          960
Chardonnay        691
Rioja             656
                 ...
Vino espumoso       4
Jerez               2
Vin Jaune           2
Chasselas           1
Dornfelder          1
Name: varietal_name, Length: 84, dtype: int64

In [45]:
all_data['varietal_name'] = np.where(all_data['varietal_name'].isin(['Blanco vinho verde']),'Vinho verde',all_data['varietal_name'])

In [46]:
all_data['varietal_name'] = np.where(all_data['varietal_name'].isin(['Blanco de Macônnais']),'Maconnais',all_data['varietal_name'])

In [47]:
all_data['varietal_name'] = np.where(all_data['varietal_name'].isin(['Tinto de Libourne']),'Libourne',all_data['varietal_name'])

In [48]:
all_data['region'] = np.where(all_data['region'].isin(['Vino Nobile di Montepulciano']),'Montepulciano',all_data['region'])

In [49]:
all_data['varietal_name'] = np.where(all_data['varietal_name'].isin(['Vino Nobile di Montepulciano']),'Sangiovese',all_data['varietal_name'])

In [50]:
all_data['region'] = np.where(all_data['region'].isin(["Montepulciano d'Abruzzo"]),'Abruzzo',all_data['region'])

In [51]:
all_data['varietal_name'] = np.where(all_data['varietal_name'].isin(["Montepulciano d'Abruzzo"]),'Montepulciano',all_data['varietal_name'])

In [52]:
all_data['varietal_name'] = np.where(all_data['varietal_name'].isin(['Saint-Joseph']),'Syrah',all_data['varietal_name'])

In [53]:
all_data['varietal_name'] = np.where(all_data['varietal_name'].isin(['Saint-Julien','Pessac-Léognan']),'Cabernet Sauvignon',all_data['varietal_name'])

In [54]:
all_data['varietal_name'] = np.where(all_data['varietal_name'].isin(['Saint-Émilion']),'Merlot',all_data['varietal_name'])

## Giving name to the type column

In [55]:
all_data['type'].value_counts()

1    11817
2     9259
Name: type, dtype: int64

In [56]:
all_data['type'] = all_data['type'].map({1:'Red', 2:'White'})
all_data['type'].value_counts()

Red      11817
White     9259
Name: type, dtype: int64

## Merging with grapes

In [70]:
grapes = pd.read_csv('update_grapes.csv')

In [71]:
merged = pd.merge(left = all_data,
        right = grapes,
        how = 'left', 
        left_on = "wine_id", 
        right_on= "wine_id")

In [72]:
merged

,wine_id,type,wine_name,country,region,varietal_name,winery,year,style_id,body,body_description,acidity_1,acidity_description,acidity_2,fizziness,intensity,sweetness,tannin,vol_ml,price_eur,num_ratings,rate,grapes_1_id,grapes_1_name,grapes_1_seoname,grapes_1_count,grapes_2_id,grapes_2_name,grapes_2_seoname,grapes_2_count,grapes_3_id,grapes_3_name,grapes_3_seoname,grapes_3_count
0,27946372,Red,Paulo Laureano Dolium Reserva,portugal,Alentejo,Tinto,Paulo Laureano,2014,2,4.0,High,3.0,High,3.36,0.0,3.97,1.67,3.25,750.0,58.00,721,4.2,67.0,Touriga Nacional,touriga-nacional,85787.0,69.0,Tinta Roriz,tinta-roriz,41047.0,68.0,Touriga Franca,touriga-franca,33763.0
1,5624201,Red,Herdade do Rocim Grande Rocim Reserva Tinto,portugal,Alentejo,Tinto,Herdade do Rocim,2013,2,4.0,High,3.0,High,3.00,0.0,4.26,2.14,3.18,750.0,72.50,1256,4.2,67.0,Touriga Nacional,touriga-nacional,85787.0,69.0,Tinta Roriz,tinta-roriz,41047.0,68.0,Touriga Franca,touriga-franca,33763.0
2,2020315,Red,Dona Maria Reserva,portugal,Alentejo,Tinto,Dona Maria,2005,2,4.0,High,3.0,High,2.98,0.0,4.11,1.73,2.79,750.0,42.00,3040,4.0,67.0,Touriga Nacional,touriga-nacional,85787.0,69.0,Tinta Roriz,tinta-roriz,41047.0,68.0,Touriga Franca,touriga-franca,33763.0
3,144779059,Red,Paulo Laureano Bacalhau Escolha Tinto,portugal,Alentejo,Tinto,Paulo Laureano,2016,2,4.0,High,3.0,High,2.88,0.0,3.92,1.64,3.09,750.0,17.00,538,4.0,67.0,Touriga Nacional,touriga-nacional,85787.0,69.0,Tinta Roriz,tinta-roriz,41047.0,68.0,Touriga Franca,touriga-franca,33763.0
4,13551606,Red,Herdade do Menir Vale de Ancho Reserva,portugal,Alentejo,Tinto,Herdade do Menir,2011,2,4.0,High,3.0,High,3.02,0.0,4.31,2.21,3.43,750.0,44.00,972,4.3,67.0,Touriga Nacional,touriga-nacional,85787.0,69.0,Tinta Roriz,tinta-roriz,41047.0,68.0,Touriga Franca,touriga-franca,33763.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21071,156300743,Red,Pirates of Palatinum Black Beard Cuvée Red,germany,Pfalz,Tinto,Pirates of Palatinum,2017,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,750.0,13.65,159,3.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21072,165752431,Red,Weingut Metzger Urbulle,germany,Pfalz,Tinto,Weingut Metzger,2019,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,750.0,19.50,217,3.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21073,154971776,Red,Serve Cuvée Guillaume,romania,Dealu Mare,Tinto,Serve,2016,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,750.0,21.00,288,3.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21074,27518454,Red,Clos de Gat Ayalon Valley,israel,Montes de Judea,Tinto,Clos de Gat,2015,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,750.0,35.55,1724,4.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21075,163015563,Red,Domaine du Castel La Vie Rouge,israel,Jerusalén,Tinto,Domaine du Castel,2020,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,750.0,26.95,1600,3.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Saving changes, just in case

In [73]:
merged.to_csv('all_data.csv',index = False)
merged.to_sql('all_data', con = engine, if_exists = 'replace', index = False )

21076

## Checking and dealing with NaNs

In [74]:
merged.isna().sum()

wine_id                   0
type                      0
wine_name                 0
country                   0
region                    0
varietal_name             0
winery                    0
year                      0
style_id                  0
body                   2898
body_description       2905
acidity_1              2898
acidity_description    2905
acidity_2              2898
fizziness              2898
intensity              2898
sweetness              2898
tannin                 2898
vol_ml                   50
price_eur                50
num_ratings               0
rate                      0
grapes_1_id            2829
grapes_1_name          2829
grapes_1_seoname       2829
grapes_1_count         2829
grapes_2_id            2829
grapes_2_name          2829
grapes_2_seoname       2829
grapes_2_count         2829
grapes_3_id            2829
grapes_3_name          2829
grapes_3_seoname       2829
grapes_3_count         2829
dtype: int64

In [75]:
merged[merged['vol_ml'].isna()].head()

,wine_id,type,wine_name,country,region,varietal_name,winery,year,style_id,body,body_description,acidity_1,acidity_description,acidity_2,fizziness,intensity,sweetness,tannin,vol_ml,price_eur,num_ratings,rate,grapes_1_id,grapes_1_name,grapes_1_seoname,grapes_1_count,grapes_2_id,grapes_2_name,grapes_2_seoname,grapes_2_count,grapes_3_id,grapes_3_name,grapes_3_seoname,grapes_3_count
4990,161885318,White,Quinta da Romaneira Reserva Branco,portugal,Douro,Blanco,Quinta da Romaneira,2019,133,2.0,Low,3.0,High,3.75,0.0,2.82,1.72,0.0,NaN,NaN,786,4.0,67.0,Touriga Nacional,touriga-nacional,85787.0,69.0,Tinta Roriz,tinta-roriz,41047.0,68.0,Touriga Franca,touriga-franca,33763.0
4991,166633490,White,Quinta de Cidrô Chardonnay,portugal,Duriense,Blanco,Quinta de Cidrô,2020,133,2.0,Low,3.0,High,3.61,0.0,3.08,1.83,0.0,NaN,NaN,3418,4.0,67.0,Touriga Nacional,touriga-nacional,85787.0,69.0,Tinta Roriz,tinta-roriz,41047.0,68.0,Touriga Franca,touriga-franca,33763.0
4992,160556916,White,Quinta do Ortigao Arinto - Bical,portugal,Bairrada,Blanco,Quinta do Ortigao,2018,133,2.0,Low,3.0,High,3.67,0.0,3.31,1.44,0.0,NaN,NaN,390,3.8,67.0,Touriga Nacional,touriga-nacional,85787.0,69.0,Tinta Roriz,tinta-roriz,41047.0,68.0,Touriga Franca,touriga-franca,33763.0
5016,145918484,White,CM Allgodao Branco,portugal,Dão,Blanco,CM,2015,133,2.0,Low,3.0,High,3.25,0.0,2.96,1.61,0.0,NaN,NaN,192,3.8,67.0,Touriga Nacional,touriga-nacional,85787.0,69.0,Tinta Roriz,tinta-roriz,41047.0,68.0,Touriga Franca,touriga-franca,33763.0
5031,163351371,White,Quinta dos Roques Dão Encruzado,portugal,Dão,Blanco,Quinta dos Roques,2020,133,2.0,Low,3.0,High,3.90,0.0,3.02,1.64,0.0,NaN,NaN,1656,3.8,67.0,Touriga Nacional,touriga-nacional,85787.0,69.0,Tinta Roriz,tinta-roriz,41047.0,68.0,Touriga Franca,touriga-franca,33763.0

In [76]:
data_to_model = merged.drop(['wine_name','winery','vol_ml','price_eur'],axis=1)

In [77]:
data_to_model

,wine_id,type,country,region,varietal_name,year,style_id,body,body_description,acidity_1,acidity_description,acidity_2,fizziness,intensity,sweetness,tannin,num_ratings,rate,grapes_1_id,grapes_1_name,grapes_1_seoname,grapes_1_count,grapes_2_id,grapes_2_name,grapes_2_seoname,grapes_2_count,grapes_3_id,grapes_3_name,grapes_3_seoname,grapes_3_count
0,27946372,Red,portugal,Alentejo,Tinto,2014,2,4.0,High,3.0,High,3.36,0.0,3.97,1.67,3.25,721,4.2,67.0,Touriga Nacional,touriga-nacional,85787.0,69.0,Tinta Roriz,tinta-roriz,41047.0,68.0,Touriga Franca,touriga-franca,33763.0
1,5624201,Red,portugal,Alentejo,Tinto,2013,2,4.0,High,3.0,High,3.00,0.0,4.26,2.14,3.18,1256,4.2,67.0,Touriga Nacional,touriga-nacional,85787.0,69.0,Tinta Roriz,tinta-roriz,41047.0,68.0,Touriga Franca,touriga-franca,33763.0
2,2020315,Red,portugal,Alentejo,Tinto,2005,2,4.0,High,3.0,High,2.98,0.0,4.11,1.73,2.79,3040,4.0,67.0,Touriga Nacional,touriga-nacional,85787.0,69.0,Tinta Roriz,tinta-roriz,41047.0,68.0,Touriga Franca,touriga-franca,33763.0
3,144779059,Red,portugal,Alentejo,Tinto,2016,2,4.0,High,3.0,High,2.88,0.0,3.92,1.64,3.09,538,4.0,67.0,Touriga Nacional,touriga-nacional,85787.0,69.0,Tinta Roriz,tinta-roriz,41047.0,68.0,Touriga Franca,touriga-franca,33763.0
4,13551606,Red,portugal,Alentejo,Tinto,2011,2,4.0,High,3.0,High,3.02,0.0,4.31,2.21,3.43,972,4.3,67.0,Touriga Nacional,touriga-nacional,85787.0,69.0,Tinta Roriz,tinta-roriz,41047.0,68.0,Touriga Franca,touriga-franca,33763.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21071,156300743,Red,germany,Pfalz,Tinto,2017,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,159,3.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21072,165752431,Red,germany,Pfalz,Tinto,2019,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,217,3.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21073,154971776,Red,romania,Dealu Mare,Tinto,2016,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,288,3.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21074,27518454,Red,israel,Montes de Judea,Tinto,2015,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1724,4.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21075,163015563,Red,israel,Jerusalén,Tinto,2020,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1600,3.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [78]:
data_to_model = data_to_model.dropna()
data_to_model.shape

(18171, 30)

## Saving again the progress

In [79]:
data_to_model.to_csv('data_to_model.csv',index = False)
data_to_model.to_sql('data_to_model', con = engine, if_exists = 'replace', index = False )

18171